### ISSUE TITLE
getting rid of `parameters` dependency

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#10]
Functions where it is needed and can't be avoided.

- `principal_components`

https://github.com/easystats/datawizard/blob/6846aa40119d401039f79a8a7e85d7391857e26c/R/principal_components.R#L396

- `factor_analysis`

https://github.com/easystats/datawizard/blob/4c88f8d076ddd1823461e0c201f850672990e9ad/R/factor_analysis.R#L70-L88

**Comment by IndrajeetPatil** [comment]
@strengejacke What do you think? Should these functions stay in `parameters`?

**Comment by strengejacke** [comment]
Maybe for now, yes.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Is this okay with you? I know you really wanted these functions to be here.
