### ISSUE TITLE
Attending to deviations in `weighted_median()` values from expected

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#102]
There is slight difference between `weighted_median()` values between these two packages:

``` r
library(sjstats)

x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15

weighted_mean(x, wt)
#> [1] 3.453333
weighted_median(x, wt)
#> [1] 3.5
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

``` r
library(datawizard)

x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15

weighted_mean(x, wt)
#> [1] 3.453333
weighted_median(x, wt)
#> [1] 3.653333
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

_Originally posted by @IndrajeetPatil in https://github.com/easystats/datawizard/issues/101#issuecomment-1064424891_

**Comment by strengejacke** [comment]
btw, there's a longer list of weighted-functions, which would be nice to have in _datawizard_, too:
https://strengejacke.github.io/sjstats/reference/weighted_sd.html

**Comment by IndrajeetPatil** [comment]
Related to #12. 

Yes, I agree that more of _sjstats_ can be moved here. I also want to export [this](https://github.com/easystats/datawizard/blob/08924f153ba456c4ecf6a8f7286de5b6c73da289/R/utils.R) function.

I think we can have a new section for statistical functions.
