### ISSUE TITLE
Question about arg `range` in `data_reverse()`

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#106]
Maybe I'm missing something, but I don't understand how the `range` argument works in `data_reverse()`:
```r
> data_reverse(c(1, 3, 4), range = c(0, 4))
[1] 3 1 0
```
Since all values are in the range, I would intuitively expect that this function returns `[1] 4 3 1` instead. Am I missing something? Could you add some details about the expected behavior when all values aren't in `range`?

Also, in the code, I think the following lines:
https://github.com/easystats/datawizard/blob/280acc9481402d972799cd5be627f9968bc1ed29/R/data_reverse.R#L73-L78
could be simplified since:
```r
(new_max - new_min) / (max - min) == (min-max)/(max-min) == -1
```

**Comment by bwiernik** [comment]
The linked line only equals -1 in the case that the range argument is not specified. If the user provides a different range (eg, if no cases in the data used the maximum response point), then the values can differ.

**Comment by etiennebacher** [comment]
@bwiernik Thanks for the explanation, it's much clearer.

> The linked line only equals -1 in the case that the range argument is not specified. If the user provides a different range (eg, if no cases in the data used the maximum response point), then the values can differ.

I disagree because whatever the values of `min` and `max`, `new_min = max` and `new_max = min`, so:
```
   (new_max - new_min) / (max - min) * (x - min) + new_min) 
== (min - max) / (max - min) * (x - min) + max
== -1 * (x - min) + max 
== min - x + max
```
I'm writing a few tests for `data_reverse()` and they also work with `out <- as.vector(min - x + max)`. I don't know if there's a "strict" formula to reverse a vector, but this puzzled me a bit (but maybe it's not that important).
