### ISSUE TITLE
Should we be exporting string utilities?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#107]
They have been there for a while in the internals, but I am not sure if they are actually useful in the ecosystem or just general purpose utilities that might be helpful for some:

https://github.com/easystats/datawizard/blob/776856fd688502ffed02f7ebe09a87ae7f6b4d24/R/utils_strings.R

**Comment by IndrajeetPatil** [comment]
@strengejacke Do we need any of these, or can I remove them?

**Comment by strengejacke** [comment]
not sure, are these in use anywhere in _datawizard_? Else, remove.

**Comment by etiennebacher** [comment]
These functions are not used in `datawizard` or `report`. Should we remove them? They're not hard to reimplement if needed

**Comment by etiennebacher** [comment]
yup
