### ISSUE TITLE
Suggestion for new package covering missing stat functions

### ISSUE THREAD

**Issue by msberends** [easystats/datawizard#12]
Would it be an idea to add another package with stat functions you would expect to be in `stats` but they are not?

Harmonic mean, geometric mean, mode, correlation of variance, standard errors, these kind of things? I could think of tens of obvious functions.

**Comment by IndrajeetPatil** [comment]
Some of these functions have already been added in this repo, while there are open issues for the rest (https://github.com/easystats/datawizard/issues/232, https://github.com/easystats/performance/issues/433, etc.).

So I am going to close the current issue.
