### ISSUE TITLE
Export select helper

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#125]
The current `.select_nse` is not exported, yet it's likely that we will need it throughout the verse. Should we export it directly? Or somehow allow its usage via `data_findcols()`, which was initially meant to fulfil that role:

https://github.com/easystats/datawizard/blob/da3e9f8769f245c34231f2e62c7eccf91fcbeb22/R/data_findcols.R#L22-L31

**Comment by strengejacke** [comment]
Yes, this is what I thought, too, when I added select helpers to all the different functions. When we would change `data_findcols()`, it ends up just calling the select-helper function. I think we should change data_findcols, too.

**Comment by strengejacke** [comment]
This will break code in some places:

https://github.com/search?q=org%3Aeasystats+data_findcols&type=code

We can do two things: add arguments `select` and `exclude` (and the end of the argument list) and keep the old arguments for now, so we have a smooth transition. Or, simply add a new function and deprecate `data_findcols()` later?

**Comment by DominiqueMakowski** [comment]
> add arguments select and exclude 

I am okay with just replacing and having a hard transition ^^, or as you say we keep the old args and deprecate them

> simply add a new function

If you have a better name in mind, sure


It seems like it's gonna be a big round of CRAN-update anyway

**Comment by IndrajeetPatil** [comment]
Yeah, adding a new function might be the way to go here.

I like: `find_columns()`. 

Not `data_find_columns()`; `data_` prefix is redundant here because by definition columns can only be present in columnar data frame structure.

**Comment by strengejacke** [comment]
> Not `data_find_columns()`; `data_` prefix is redundant here because by definition columns can only be present in columnar data frame structure.

Makes sense to me.

**Comment by DominiqueMakowski** [comment]
I was about to say "but what about the data_* prefix consistency" but then we also have lots of `find_*` (mostly in insight) so it's good :)
