### ISSUE TITLE
new functions to move from `parameters`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#13]
@strengejacke Anything else you would add here?

- [ ] `skewness`
- [ ] `kurtosis`
- [ ] `describe_distribution`
- [ ] `smoothness`
- [ ] `check_multimodal`

For backward compatibility, these will be re-exported by `parameters`

**Comment by strengejacke** [comment]
I haven't looked closer at this, but the above suggestions look fine.
