### ISSUE TITLE
get_columns: considerations

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#136]
https://github.com/easystats/datawizard/blob/617f9479813380e54f0b13d170d6e9c53359051c/R/data_findcols.R#L69-L106

Shouldn't `get_columns()` be simply `data[, find_columns(data, ...), drop = FALSE]` ?

**Comment by strengejacke** [comment]
Usually, yes. But I was uncertain of the behaviour from `parent.frame()` and the evaluation from environments, so I decided to go the safer way. But feel free to test if the other option works, too. I think there should be enough tests to detect any failures.

**Comment by DominiqueMakowski** [comment]
The function should also probably preserve attributes? Otherwise it leads to cases like here where the "95%" ci info gets stripped 

``` r
r <- correlation::correlation(iris)

head(r)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter1   |   Parameter2 |     r |         95% CI | t(148) |         p
#> -------------------------------------------------------------------------
#> Sepal.Length |  Sepal.Width | -0.12 | [-0.27,  0.04] |  -1.44 | 0.152    
#> Sepal.Length | Petal.Length |  0.87 | [ 0.83,  0.91] |  21.65 | < .001***
#> Sepal.Length |  Petal.Width |  0.82 | [ 0.76,  0.86] |  17.30 | < .001***
#> Sepal.Width  | Petal.Length | -0.43 | [-0.55, -0.29] |  -5.77 | < .001***
#> Sepal.Width  |  Petal.Width | -0.37 | [-0.50, -0.22] |  -4.79 | < .001***
#> Petal.Length |  Petal.Width |  0.96 | [ 0.95,  0.97] |  43.39 | < .001***
#> 
#> p-value adjustment method: Holm (1979)
#> Observations: 150

r <- datawizard::get_columns(r, c("r", "CI_low", "CI_high"))

head(r)
#> r     |             CI
#> ----------------------
#> -0.12 | [-0.27,  0.04]
#> 0.87  | [ 0.83,  0.91]
#> 0.82  | [ 0.76,  0.86]
#> -0.43 | [-0.55, -0.29]
#> -0.37 | [-0.50, -0.22]
#> 0.96  | [ 0.95,  0.97]
attributes(r)
#> $names
#> [1] "r"       "CI_low"  "CI_high"
#> 
#> $row.names
#> [1] 1 2 3 4 5 6
#> 
#> $class
#> [1] "easycorrelation"     "see_easycorrelation" "parameters_model"   
#> [4] "easycor_test"        "data.frame"
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
#141 should fix this

**Comment by strengejacke** [comment]
I added some more tests, to make sure `data_reorder()` or `data_remove()` also preserve attributes (they did already). That's nice, because it doesn't break our print methods! Are there any other functions in _datawizard_ that need to preserve attributes?

**Comment by DominiqueMakowski** [comment]
> Are there any other functions

We'll find them little by little :)

I wonder if we should add `data_select()` as an alias to get_columns, so that it's closer to tidyverse (and preserves the of my chain of `data_*` functions ^^)

**Comment by strengejacke** [comment]
> I wonder if we should add data_select() as an alias to get_columns

I was thinking about this, too. The only reason against this is probably that we have the find/get pair here, and adding an alias would somehow break this logic. On the other hand, it's just an alias, and users would probably rather look for `data_something()` than `get_()`, if all major data wrangling functions start with `data_`.
