### ISSUE TITLE
"tidyselect" helpers

### ISSUE THREAD

**Issue by bwiernik** [easystats/datawizard#14]
Would be nice to implement some of the basic tidyselect helpers, such as for use in `reshape_longer()` and `reshape_wider()`. This can be done with base.

**Comment by strengejacke** [comment]
https://github.com/strengejacke/sjmisc/blob/master/R/select_helpers.R

**Comment by strengejacke** [comment]
And here's my base-R function to evaluate dots, similar to `dplyr::select()` et al.
https://github.com/strengejacke/sjlabelled/blob/master/R/utils_get_dots.R

_Originally posted by @strengejacke in https://github.com/easystats/datawizard/issues/4#issuecomment-856309303_

**Comment by bwiernik** [comment]
Here is NSE in base R https://github.com/psychmeta/psychmeta/blob/8b2c0a12634bc2eee348d2b5ff33ac8cab82de2a/R/ma_r.R#L634

**Comment by IndrajeetPatil** [comment]
I've ported over the `sjmisc` and `sjlabelled` helpers.

**Comment by strengejacke** [comment]
We would then probably need to revise `data_reshape()`'s API (https://github.com/easystats/datawizard/blob/master/R/data_reshape.R), else we could use select helpers only for one argument (`cols`), not combine them unless we would evaluate `...` instead.

**Comment by bwiernik** [comment]
The reshape functions should just use cols. The tidyr pivot functions also don't use ... so that is consistent.

**Comment by bwiernik** [comment]
What I would like to do is be able to run, eg:

`reshape_longer(iris, cols = col_starts_with("petal"))`

**Comment by strengejacke** [comment]
Any news on this issue?

**Comment by bwiernik** [comment]
The new extract function has code for NSE. We can copy that to other functions or add a helper

**Comment by strengejacke** [comment]
Looks like the code

```r
  nl <- as.list(seq_along(data))
  names(nl) <- names(data)

  select <- eval(substitute(select), nl, parent.frame())
```

compares the input (bare column name) to a named list - for the expression of select helpers, we have no "unique" token, right? We don't know before that someone uses `col_starts_with("petal")`, because `"petal"` is unknown, so we don't have matching "tokens" and list names... ???

**Comment by bwiernik** [comment]
I'm not following

**Comment by strengejacke** [comment]
> I'm not following

Yeah, that's my typical feeling in many situations 😄 

`eval(substitute(select), nl, parent.frame())` works for, say, `cyl`, because `cyl` is also the name of an element in `nl`. However, if we use `cols = col_starts_with("petal")`, then `substitute()` will create a string representation of that expression. However, how do we get the list `nl`, where we match that expression with the list elements' names?

**Comment by strengejacke** [comment]
We currently have:

- bare names
- quoted names
- regex pattern (depending on the function)
- `contains()`
- `starts_with()`
- `ends_with()`
- numeric, ranges (like `1:3`)

I can try to implement this for the reshape-functions. What kind of select helpers are missing? Should we provide explicit docs for the select helpers?

**Comment by bwiernik** [comment]
Does everything still work as expected if you library() dplyr or tidyselect?

In tidyselect, matches() is what matches a regex. contains() only does literal matching. We might want to be consistent with that?

num_range() might be useful https://tidyselect.r-lib.org/reference/starts_with.html

**Comment by strengejacke** [comment]
> Does everything still work as expected if you library() dplyr or tidyselect?

Yes, I didn't have any conflicts. `matches()` is added, too.
