### ISSUE TITLE
Informative error messages for dates

### ISSUE THREAD

**Issue by bwiernik** [easystats/datawizard#149]
We should have informative error messages for Date, POSIXt, and POSIXct variables for all of our functions. 

Just had a student very confused by an error message from data_to_numeric() with these opaque class names

**Comment by strengejacke** [comment]
What would you prefer? In `data_rescale()`, factors are silently ignored (returned as is). In `data_reverse()`, unsupported classes are not captured. 

I now added a `.deault` method:

```r
data_reverse.default <- function(x, verbose = TRUE, ...) {
  if (isTRUE(verbose)) {
    message(insight::format_message(paste0("Variables of class '", class(x)[1], "' can't be recoded and remain unchanged.")))
  }
  x
}
```

Should we in general silently ignore unsupported classes, or yield a message?

**Comment by bwiernik** [comment]
For these, we should have an error message that says "Date variables (class 'class') cannot be converted to numeric." The issue is that POSIXct is really opaque to new users

**Comment by strengejacke** [comment]
I would not stop here, else it's really a hassle if you need to identify the problematic variables in a data frame, remove them prior to data wrangling and add them probably back later

**Comment by strengejacke** [comment]
That's why I did this change:
https://github.com/easystats/datawizard/commit/01cbb59c1bde4553d72585b08895bbfabcf6bb64

**Comment by bwiernik** [comment]
That warning is great. Would it be a good idea to add methods for POSIXct/t to clarify what these classes are for new users?

**Comment by strengejacke** [comment]
> Would it be a good idea to add methods for POSIXct/t to clarify what these classes are for new users?

Not only for new users, I can't tell much about that class, either ;-)

**Comment by bwiernik** [comment]
Awesome, maybe also include the actual class name in the message as well. And it should apply to POSIXct as well as POSIXt
