### ISSUE TITLE
Potential improvements to `reshape_*()`

### ISSUE THREAD

**Issue by bwiernik** [easystats/datawizard#15]
- [ ] Work with rownames and not only row numbers
- [x] longer: argument: `names_pattern`
- [ ] longer: `".value"` special name
- [ ] wider: arguments: 
    - [x] `names_prefix`
    - [x] `names_glue`
    - [ ] `names_sort`
    - [ ] `names_repair`
    - [x] `values_fill`
    - [ ] `values_fn`
- [x] wider: `names_sep` alias for `sep` argument
- [x] Non-standard evaluation in `reshape_wider()` for `names_from` and `values_from`? (need an example where this is needed)
- [ ] `tidyr::pivot_longer()` examples:
    - [x] 3
    ```r
    tidyr::who |> 
      datawizard::reshape_longer(cols = 5:60,
                                 names_to = c("diagnosis", "gender", "age"),
                                 names_pattern = "new_?(.*)_(.)(.*)",
                                 values_to = "count")
     ```
    - [ ] 4
    ```r
    anscombe |> 
      datawizard::reshape_longer(cols = colnames(anscombe),
                                 names_to = c(".value", "set"),
                                 names_pattern = "(.)(.)"
     ```
- [ ] `tidyr::pivot_wider()` examples:
    - [x] 2
    ```r
     tidyr::fish_encounters |> 
        datawizard::reshape_wider(names_from = "station", values_from = "seen", values_fill = 0)
     ```
     - [ ] 5
     ```r
     tidyr::us_rent_income |> 
         datawizard::reshape_wider(names_from = "variable",
                                   names_glue = "{variable}_{.value}",
                                   values_from = c("estimate", "moe"))
     ```
     - [ ] 6
     ```r
     warpbreaks[c("wool", "tension", "breaks")] |> 
         datawizard::reshape_wider(
             names_from = "wool",
             values_from = "breaks",
             values_fn = mean
         )
     ```

**Comment by IndrajeetPatil** [comment]
@strengejacke How much of this is now supported by the new functionality that has been added for this release?

**Comment by strengejacke** [comment]
I'm not 100% sure, but I think none of those is currently supported.

**Comment by strengejacke** [comment]
Questions: 
- What does `names_pattern` do?
- How does it work together with length of `name_to` > 1?
-

**Comment by bwiernik** [comment]
If `names_to` has length >1, the names are sent to multiple columns, with one part of the name in each column. The column name is split into parts either by `names_sep` (eg, `names_to = c("group", "time"), sep = "_"` would split `control_pre` into two parts and send "control" to "group" and "pre" to "time". 

For more complicated column names, instead of `names_sep`, you can use `names_pattern` to give a regex that is used to split the names. Each capture group in that regex is one component

**Comment by etiennebacher** [comment]
I think some args of `pivot_wider` will be hard to translate to base R or are not super essential:
* `names_glue` looks hard to implement with base R only
* `names_sort`, `names_vary`, `names_expand` and `names_repair` don't seem essential to me, but could be implemented later
* `values_fn` is the same as applying the function and then pivoting:
``` r
library(dplyr)
library(tidyr)

warpbreaks[c("wool", "tension", "breaks")] |> 
  tidyr::pivot_wider(
    names_from = "wool",
    values_from = "breaks",
    values_fn = "mean"
  )
#> # A tibble: 3 × 3
#>   tension     A     B
#>   <fct>   <dbl> <dbl>
#> 1 L        44.6  28.2
#> 2 M        24    28.8
#> 3 H        24.6  18.8

warpbreaks[c("wool", "tension", "breaks")] %>% 
  group_by(wool, tension) %>% 
  summarize(breaks = mean(breaks)) %>% 
  ungroup %>% 
  pivot_wider(names_from = "wool", values_from = "breaks")
#> `summarise()` has grouped output by 'wool'. You can override using the
#> `.groups` argument.
#> # A tibble: 3 × 3
#>   tension     A     B
#>   <fct>   <dbl> <dbl>
#> 1 L        44.6  28.2
#> 2 M        24    28.8
#> 3 H        24.6  18.8
```

<sup>Created on 2022-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by etiennebacher** [comment]
Most of these features are not essential and the objective is not to mimic the `tidyr::pivot_` functions at 100%. Closing this but feel free to reopen if one of these features would be useful for the development of other `easystats` packages.
