### ISSUE TITLE
including mode for the distribution in `describe_distribution`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#160]
Saw some discussion on Twitter about how base-R doesn't have a function to calculate mode. So  was wondering if it might be a good idea for us to include this info.

``` r
library(parameters)

describe_distribution(mtcars$wt)
#> Mean |   SD |  IQR |        Range | Skewness | Kurtosis |  n | n_Missing
#> ------------------------------------------------------------------------
#> 3.22 | 0.98 | 1.19 | [1.51, 5.42] |     0.47 |     0.42 | 32 |         0

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
We should include the mode for categorical variables and the map for continuous

**Comment by bwiernik** [comment]
In light of https://github.com/easystats/datawizard/issues/232, I think we should add a `metrics` argument like in `performance::model_performance()` that enumerates the stats to provide, with something like the current set as the default value.

**Comment by etiennebacher** [comment]
Closing in favor of #46
