### ISSUE TITLE
CRAN Update needed before 05-16

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#163]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_datawizard.html>.

Please correct before 2022-05-16 to safely retain your package on CRAN.

The CRAN Team

## TODO

- [x]  #161 
- [x] #162

**Comment by strengejacke** [comment]
I think this has been fixed already:
https://github.com/easystats/datawizard/commit/c1db497b2bc293eb12959449daf52d7fa8a192aa

**Comment by IndrajeetPatil** [comment]
Cool. 

I have added a TODO list to keep track of what needs to be done before I can submit a revision.

**Comment by strengejacke** [comment]
I think #162 is ready to merge.

**Comment by strengejacke** [comment]
insight is still under review, due to revdep issues

**Comment by IndrajeetPatil** [comment]
Still no news about _insight_? 

We are getting dangerously close to the deadline for _datawizard_. 

Should I request an extension?

**Comment by IndrajeetPatil** [comment]
Sounds good.

**Comment by strengejacke** [comment]
_insight_ update is on CRAN.
