### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by mattansb** [easystats/datawizard#17]
- [x] Some of the docs are referencing functions that use to be coupled with these functions in their previous homes. (e.g., standardize references model standardization).
- [x] Docs from the functions previously in `effectsize` need to have md formatting turned on.

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/easystats/datawizard/commit/1106624cce97128f72a17427bc540e344e18049b

I am going to read through all the docs one more time to make sure that there are no out of date references, apart from the one you pointed out.
