### ISSUE TITLE
Rename data_extract()

### ISSUE THREAD

**Issue by bwiernik** [easystats/datawizard#172]
The alias for `data_extract()` (`extract()`) conflicts with a *tidyr* function, so we should consider a rename. It's a variant on `dplyr::pull()` with some more support for non-tidyverse-style data frames (e.g., acknowledges the existence of rownames). 

Any thoughts on alternative verbs? Or should we just drop the alias?

**Comment by DominiqueMakowski** [comment]
I'd drop the alias

**Comment by strengejacke** [comment]
Yes, agree

**Comment by strengejacke** [comment]
Shouldn't all the example also be fixed? And maybe other occurrences in the code?

**Comment by bwiernik** [comment]
We alternatively have `pluck()`, `yank()`, and `extricate()` 😜

**Comment by bwiernik** [comment]
pluck() is growing on me
