### ISSUE TITLE
Fix failing test for `data_read()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#184]
```r
── Error (test-data_read.R:14:3): data_read ────────────────────────────────────
Error in `curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress)`: SSL certificate problem: certificate has expired
Backtrace:
    ▆
 1. └─datawizard::data_read("https://stats.idre.ucla.edu/stat/data/binary.csv") at test-data_read.R:14:2
 2.   └─datawizard:::.read_text(path, encoding, verbose, ...) at datawizard/R/data_read.R:63:2
 3.     └─data.table::fread(input = path, ...) at datawizard/R/data_read.R:195:4
 4.       └─curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) at data.table/R/fread.R:64:8
```

**Comment by IndrajeetPatil** [comment]
Is there some other remote dataset we can read?

**Comment by etiennebacher** [comment]
How about this one from package {vroom}? https://raw.githubusercontent.com/tidyverse/vroom/main/inst/extdata/mtcars-4.csv

**Comment by IndrajeetPatil** [comment]
I think we can just copy it to our repo instead of using a URL to avoid possibility of a failing test in case of no connection.

**Comment by etiennebacher** [comment]
Seems like the test is not failing anymore but to avoid relying on https://stats.idre.ucla.edu, we can just use one the csv files in {circus}. Also, we can put `skip_if_offline()` at the beginning of the file
