### ISSUE TITLE
remove gif in readme?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#188]
Personally I find it distracting (especially since it's the first thing we see on datawizard homepage)

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski WDYT?

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/sUzZwE9AgI8iA/giphy.gif)

**Comment by DominiqueMakowski** [comment]
Let's put it lower then 😅  

but we should improve the song too:

*Hockety pockety wockety wack, [...] \*ack*
*Hockety pockety wockety wock, messy data is in shock*
*Hockety pockety wockety woss, you can cite i-it from JOSS*  <sub>(not yet but soon)</sub>
*Hockety pockety wockety wass, datawizard saves your ass!*
