### ISSUE TITLE
Streamline data transformation code

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#19]
4 functions, namely `standardize`, `normalize`, `ranktransform` and `change_scale` have a very similar code, which makes it 1) unnecessary lengthy and 2) harder to maintain. It could be streamlined with a nice internal.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski and @mattansb A lot has changed in the last 2 years with these functions, and I am wondering if this issue is still relevant?

**Comment by mattansb** [comment]
No idea 👀

**Comment by strengejacke** [comment]
Yes, I think the core work is now in `.process_std_center()`, which is called from standardize and center. Also, the data frame methods now all call `.select_nse()` and then just s/lapply over the remaining columns, using the numeric/factor-methods.
