### ISSUE TITLE
Remove the `data_*()` prefix from statistical transformation function names

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#197]
> I also feel that we should remove the `data_*()` prefix from statistical transformation function names.
>
>_Originally posted by @IndrajeetPatil in https://github.com/easystats/datawizard/issues/183#issuecomment-1178881064_

Moved here, since it is not related to the vignette about equivalence with tidyverse

**Comment by IndrajeetPatil** [comment]
Specifically, here is what the function names look like right now:

# Preparation

- data_filter()
- data_select()
- data_to_long()
- data_to_wide()
- data_rotate()
- data_rename()
- data_relocate()
- data_join()

# Transformation:

- standardize()
- normalize()
- center()
- degroup()
- winsorize()
- data_cut()
- data_recode()
- data_shift()

And I am wondering if the following should lose their `data_` prefix:

- data_cut()
- data_recode()
- data_shift()

**Comment by bwiernik** [comment]
The problem is cut() is in base and recode() is in dplyr. shift() is in data.table--that's probably less of a collision issue, but I imagine we probably have a fair number of data.table users

**Comment by etiennebacher** [comment]
How about:
1. `data_cut` -> `categorize`
2. ?
3. `data_shift` -> `move`

`reverse_scale` is already an alias for `data_rescale`. 

I don't know which is better, removing `data_` for these functions or not. I just want to say that I like having the prefix for the data prep functions, it's easy to see which functions are available with autocomplete. So if you want to remove `data_` maybe it would be a good idea to replace it with another prefix for all data transformation functions. For example, having a prefix `do_` would give the following:
* `do_standardize()`
* `do_normalize()`
* `do_center()`
* `do_degroup()`
* `do_winsorize()`
* `do_recode()`
* etc.

`use_`, `make_` or `apply_` could be other prefixes.

**Comment by mattansb** [comment]
cut > discretize?
recode > revalue?
shift > I like translate, or slide (like a slide ruler), or "add" 😅?

I think it's a good idea to have dedicated `data_*` functions for data frames. I've found that students don't often fully comprehend that difference classes have different methods for the same function. So having separate functions for dfs sounds good (or having aliases for the methods e.g. `data_standardize <- standardize.data.frame`).

**Comment by bwiernik** [comment]
I would prefer not to have prefixes for vector functions

**Comment by bwiernik** [comment]
reverse_scale() is not exactly an alias. It has fewer arguments and is designed to provide a more intuitive function for using rescale() to reverse

**Comment by bwiernik** [comment]
I think I like the idea of documenting the data frame methods all together.

**Comment by bwiernik** [comment]
My votes:

1. cut -> categorize
2. recode -> relabel 
3. shift -> slide 
3. reverse -> reverse
4. rescale -> rescale
5. `data_to_type` -> `to_type`


(For 2, `forcats::fct_relabel()` is a different function that is rarely used AFAICT)

`data_` prefixes only for data frame methods

**Comment by mattansb** [comment]
I second all of what @bwiernik says, except for `relabel` - from the docs recode is (also?) for chancing numeric values to other number values.

**Comment by DominiqueMakowski** [comment]
Whatever we decide for Wmwe should avoid having conflicts with base R at all cost 

Why not having another alias for all these transfo functions like:

values_recode(), values_reverse() etc 

so that data_ is meant primarily for dfs and values_ for vectors. It's a bit longer to type but autocompletion much

**Comment by mattansb** [comment]
[`yardstick`](https://yardstick.tidymodels.org/reference/mcc.html) has a convention where data frame function's gets the measure name, and vectors get a `*_vec` suffix. 
I think we should have just one, and I think the `data_*` for dfs makes more sense.

**Comment by bwiernik** [comment]
of the available synonyms for "recode", "relabel" seemed the least objectionable. A conflict with dplyr is nearly as bad as a conflict with base IMO. I don't think that "relabel" precludes numeric values--the function changes the numeric labels used for different categories. And in contrast to rescale(), it does it through 1:1 mapping of values/labels, rather than a linear or other mathematical transformation

**Comment by strengejacke** [comment]
> 1. cut -> categorize

agree-

> 2. recode -> relabel

I prefer recode here (or put differently: I don't like "relabel"), because relabel sounds like changing value labels (I always have the association with _labelled data_)

> 3. shift -> slide

agree.

> 4. reverse -> reverse

agree.

> 5. rescale -> rescale

agree.

> 6. `data_to_type` -> `to_type`

agree.

**Comment by bwiernik** [comment]
We can't do `recode()` because of `dplyr::recode()`. What other options do we have?

**Comment by etiennebacher** [comment]
`recode` -> `revalue`? (cf @mattansb proposition)

**Comment by bwiernik** [comment]
That word means "reassess the worth of something"

**Comment by mattansb** [comment]
convert?

**Comment by bwiernik** [comment]
I think that suggests type conversion (numeric -> factor or character, etc.)

**Comment by IndrajeetPatil** [comment]
The problem with `change_code()` is that it breaks the single work pattern for other transformation functions:

  - `data_cut()`     -> `categorize()`
  - `data_recode()`  ->  ???
  - `data_shift()`   -> `slide()`
  - `data_reverse()` -> `reverse()`
  - `data_rescale()` -> `rescale()`
  
But I also agree that `recode()` (because of dplyr), `relabel()`, `revalue()` also don't sound good.

So I guess `change_code()` is the least bad option? Everyone else agrees about this choice?

**Comment by IndrajeetPatil** [comment]
> data_to_type -> to_type

@bwiernik Which function is this? Definitely not in _datawizard_.

**Comment by bwiernik** [comment]
data_to_factor, data_to_numeric, etc. that family of functions

**Comment by IndrajeetPatil** [comment]
Ah, I see! Got it. 

In that case, the following comment is irrelevant:

> The problem with change_code() is that it breaks the single work pattern for other transformation functions:

**Comment by IndrajeetPatil** [comment]
If we're renaming `data_to_numeric()` to `to_numeric()`, what should the existing `to_numeric()` should be renamed to? 

How about `coerce_to_numeric()`

https://github.com/easystats/datawizard/blob/3a3529b1e016faf79e41a65863438b1bf97ab419/R/data_to_numeric.R#L262-L268

**Comment by strengejacke** [comment]
We could integrate it, having an argument that either preserves factors or coerces to numeric.

Have you checked other packages for usage of `to_numeric()`?

**Comment by IndrajeetPatil** [comment]
> We could integrate it, having an argument that either preserves factors or coerces to numeric.

Yeah, that sounds better.

> Have you checked other packages for usage of `to_numeric()`?

Few [do](https://rdrr.io/search?q=to_numeric), but I'd worry only about _tidyverse_ namespace collisions.

**Comment by strengejacke** [comment]
> Few [do](https://rdrr.io/search?q=to_numeric), but I'd worry only about tidyverse namespace collisions.

Sorry, I was referring to internal uses of `to_numeric()` in across _easystats_, so we don't break code. :-)

**Comment by IndrajeetPatil** [comment]
AFAICT, it is used only in one place: https://github.com/easystats/modelbased/blob/671ba596eeb350536d08290ee97248145d7fdba0/R/visualisation_recipe.estimate_grouplevel.R#L41

So we can definitely make this breaking change.

**Comment by IndrajeetPatil** [comment]
The _easystats_ ecosystem after the renaming. 

![the-it-crowd-moss-the-it-crowd](https://user-images.githubusercontent.com/11330453/180638530-cca0c062-be39-4e46-ba07-83ada9c32c94.gif)

I think I have put out all the fires now, so should be fine.
