### ISSUE TITLE
GHA for render-readme broke again

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#208]
From GHA: `The workflow is not valid. .github/workflows/render-readme.yml (Line: 34, Col: 9): Unexpected value 'with'`

https://github.com/easystats/datawizard/blob/ecceea3f87202ac5f4af4f0a037396b30c6bdbd7/.github/workflows/render-readme.yml#L32-L37

**Comment by IndrajeetPatil** [comment]
_Mea culpa_!

Will fix it.
