### ISSUE TITLE
Tidyverse vignette: improve explanation on selecting

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#209]
I forgot about it but there was some review required about the "selecting" section of the vignette: https://github.com/easystats/datawizard/pull/183#discussion_r911184205

I just put it here so that it doesn't get forgotten since the PR was merged.

**Comment by IndrajeetPatil** [comment]
Another thing to add to this vignette would be `data_arrange()`.

**Comment by IndrajeetPatil** [comment]
One more thing to add: `data_peek()` <=> `dplyr::glimpse()` equivalence.
