### ISSUE TITLE
Add alias `text_format()` and eventually deprecate `format_text()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#224]
`format_text()` is the black sheep of this function family. 

![image](https://user-images.githubusercontent.com/11330453/185739985-beca4fc1-efc8-4d0b-923c-9dc877e9203e.png)

**Comment by IndrajeetPatil** [comment]
This function is used only in `{report}`, so the deprecation should require just one update cycle.

**Comment by strengejacke** [comment]
Yes, sounds reasonable.
