### ISSUE TITLE
Regex argument not passed to `.select_nse()` in `datawizard::data_remove`

### ISSUE THREAD

**Issue by rempsyc** [easystats/datawizard#229]
Following up on #218, I do not understand how to use the regex argument with `datawizard::data_remove` to mimic the “contains” select helper.

`datawizard::data_remove` works with select helper:

``` r
datawizard::data_remove(
  mtcars, select = contains("pg")) |> names()
#>  [1] "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear" "carb"
```

Base R works too:

``` r
mtcars |> names()
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb"
grepl("pg", names(mtcars))
#>  [1]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
mtcars[!(grepl("pg", names(mtcars)))] |> names()
#>  [1] "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear" "carb"
```

`datawizard::find_columns` works as well:

``` r
mtcars[!(names(mtcars) %in% datawizard::find_columns(
  mtcars, select = "pg", regex = TRUE))] |> names()
#>  [1] "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear" "carb"
```

But does `datawizard::data_remove` regex work as expected?

``` r
datawizard::data_remove(
  mtcars, select = "pg", regex = TRUE) |> names()
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb"
```

I know these functions are calling `.select_nse` under the hood. For example, `datawizard::find_columns` calls `.select_nse` with the regex argument passed:
```r
columns <- .select_nse(
  select,
  data,
  exclude,
  ignore_case = ignore_case,
  regex = regex,
  verbose = FALSE)
```
However, `datawizard::data_remove` doesn’t pass the regex argument!
```r
select <- .select_nse(select, data, exclude = NULL, ignore_case)
```
I will submit a PR to fix it, if that's ok. I'm on `datawizard` version

``` r
packageVersion("datawizard")
#> [1] '0.5.1'
```

<sup>Created on 2022-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Oh yes, seems like we didn't update all internal function calls after we added the select-helper capabilities. If you open a PR, could you also add your failing example as unit-test?

**Comment by rempsyc** [comment]
Of course. Should I also update all other `data_x` functions, not just `data_remove`? I've noticed many of them are missing it too.

**Comment by strengejacke** [comment]
how can that be? shame on us... 
![homer_dimishing](https://user-images.githubusercontent.com/26301769/186272378-d812d1d0-ee67-4a14-b6bc-5fce5a823c73.gif)
