### ISSUE TITLE
Re-rename `change_code()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#233]
Before we finalize this, we should definitely decide on the new function names. Mostly, I'm not quite satisfied with `change_code()`. `recode` is a verb, and everyone would expect such a function would recode old into new values. in `change_code()`, the verb is `change`, and what can we expect if we change a code? What we actually _change_ when _recoding_ are _values_ (or factor levels, but values is maybe more generic). What do you think about `change_values()`? or maybe `recode_values()`, or `recode_variables()`.

_Originally posted by @strengejacke in https://github.com/easystats/datawizard/issues/87#issuecomment-1200449988_

**Comment by IndrajeetPatil** [comment]
The "code" being the mapping of quantities to values/labels. So the function is changing the coding scheme used. 

Maybe `change_coding()`? `change_values()` would be my second choice

_Originally posted by @bwiernik in https://github.com/easystats/datawizard/issues/87#issuecomment-1200455352_

**Comment by bwiernik** [comment]
I like `change_coding()` or `recode_values()`

**Comment by DominiqueMakowski** [comment]
recode_values() +1

**Comment by strengejacke** [comment]
ok, than let's go for `recode_values()`.

**Comment by bwiernik** [comment]
In the future, if there are lingering concerns about renaming a function or argument, I'd like to not merge or at least not release until there is consensus. Eg, we probably should have left `data_recode()` in place until we settled on an alternative everyone was happy with
