### ISSUE TITLE
replace_missing()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#243]
Would be good to have such a feature to easily replace NaNs. Currently tidy's solution doesn't allow to do simple stuff like `replace_na(df, 0)` because it requires a list for all the columns with specific imputation values. 

This function could be extended in the future to call more fancy imputation methods.

**Comment by strengejacke** [comment]
Do you mean
https://easystats.github.io/datawizard/reference/convert_to_na.html
https://easystats.github.io/datawizard/reference/replace_nan_inf.html
https://easystats.github.io/datawizard/reference/convert_na_to.html

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/13e4OMO2IVZloQ/giphy.gif)
