### ISSUE TITLE
Reduce lints

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#247]
Not possible to get rid of them completely, but we can try to reduce as much as we can:

https://github.com/easystats/datawizard/actions/workflows/lint.yaml

**Comment by etiennebacher** [comment]
I don't understand this issue, what does reducing lints mean? Is it something to do ourselves or is it done automatically in the GHA?

**Comment by IndrajeetPatil** [comment]
> Is it something to do ourselves

Yes, we need to do this ourselves. GHA just flags the lints, we need to clean them up.

I will slowly get rid of them.
