### ISSUE TITLE
Mistake in the docs of `data_peek`?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#256]
https://easystats.github.io/datawizard/reference/data_peek.html

![image](https://user-images.githubusercontent.com/52219252/188842018-c99db300-027f-4901-b16c-4ca1d96c0351.png)

It's not the case, the function only returns the variables in `select`:
``` r
library(datawizard)
data(efc)
data_peek(efc, select = starts_with("e"))
#> Data frame with 100 rows and 5 columns
#> 
#> Variable | Type    | Values                                              
#> -------------------------------------------------------------------------
#> e16sex   | numeric | 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, ... 
#> e42dep   | factor  | 3, 3, 3, NA, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 3, 3, ...
```

<sup>Created on 2022-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by etiennebacher** [comment]
In addition to that, `data_peek` has an argument `n` that is the `number of variables to display. If NULL, all variables will be shown.`. Isn't this already taken into account with for example `select = 1:3`?

**Comment by strengejacke** [comment]
Yes, true. And the docs-section was also mistakenly in `data_tabulate()`. I also removed the `n` argument, since it indeed was not necessary, and added a `Note` about showing specific variables only.
