### ISSUE TITLE
Variables selection: should we remove the use of the minus sign in front of `select`?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#258]
Most of the time, the argument “select” can be prefixed with “-” to inverse the selection, e.g:

``` r
find_columns(iris, -c("Sepal.Length"))
```

    ## [1] "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

``` r
find_columns(iris, -starts_with("Sep"))
```

    ## [1] "Petal.Length" "Petal.Width"  "Species"

However:

-   this makes the argument `exclude` useless;
-   using “-” in front of the select argument reverses “select” **except** for numeric (prefixing a number with “-” makes the selection start from the end of the dataframe), which is quite misleading IMO:

``` r
find_columns(iris, -1)
```

    ## [1] "Species"

Removing the use of this “-” sign as prefix of select would be a breaking change, but I think it’s important to improve consistency. Another option is to keep the “-” sign, but remove the `exclude` argument and remove the use of -1 to get the last column (perhaps implement something like `last_col()`?).

@easystats/core-team what do you think?

**Comment by DominiqueMakowski** [comment]
Mmh I started typing an argument in favour of keeping the minus form, but I realized that I use actually use it for both (inversing the selection and selecting the last columns...), and it's true that it's a bit inconsistent. How does the tidyverse deal with that?

**Comment by bwiernik** [comment]
What's the behavior in the select argument in base `subset`?

**Comment by etiennebacher** [comment]
> What's the behavior in the select argument in base `subset`?

It removes the first column:
``` r
subset(head(iris), select = -1)
#>   Sepal.Width Petal.Length Petal.Width Species
#> 1         3.5          1.4         0.2  setosa
#> 2         3.0          1.4         0.2  setosa
#> 3         3.2          1.3         0.2  setosa
#> 4         3.1          1.5         0.2  setosa
#> 5         3.6          1.4         0.2  setosa
#> 6         3.9          1.7         0.4  setosa
```

**Comment by strengejacke** [comment]
My 2 cents:
1) `exclude` is a "historical artefact", needed when we had a simpler implementation of `select`. We can check use cases, but maybe we can indeed remove it.
2) `select = -1` should remove the first column. Everything else is indeed inconsistent and probably confusing to less experienced users.

**Comment by bwiernik** [comment]
I agree that we should make the minus behavior consistent. I don't know that we necessarily need to remove `exclude` even if it's redundant. It's intuitive and worthwhile IMO

**Comment by etiennebacher** [comment]
While we're talking about selecting variables, do you think we should allow several patterns in `starts_with()` and friends, e.g `select = starts_with("Sep", "Petal")`?. The `tidyverse` doesn't need this because they capture the select helpers in `...` but we can just use `select`

**Comment by rempsyc** [comment]
@etiennebacher I agree it would be nice to able to select patterns.

That makes me think of another issue I had with `select`. Once I wanted to extract my scale mean for something else but it wasn't giving sensical results, and it took me a bit of time to figure out that it was extracting all items starting with the same name too…

``` r
library(datawizard)
data <- data.frame(test = 1:3, item1.test = 1:3, bad_test.item2 = 1:3)

# I want just the test column!
data_select(data, select = test)
#>   test item1.test bad_test.item2
#> 1    1          1              1
#> 2    2          2              2
#> 3    3          3              3
# Whoops?
```

But one has to put the variable name in quotes to display the correct behaviour. Perhaps it is currently expected behaviour as it is now, but it can be misleading I think. Doc says:

> Variables that will be included when performing the required tasks. Can be either a variable specified as a literal variable name (e.g., column_name),

But it doesn’t say that variables specified as a litteral variable name will be treated exactly the same as regex select helper `contains(")`.

<sup>Created on 2022-09-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by etiennebacher** [comment]
> But it doesn’t say that variables specified as a litteral variable name will be treated exactly the same as regex select helper contains(").

This is not the expected behavior, and the selection in your example works correctly with the changes I made in #255 (not merged for now).
