### ISSUE TITLE
Release version `0.6.0`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#261]
- [x] #255 
- [x] #258
- [x] #260

**Comment by etiennebacher** [comment]
I'd like to fix #258 as well (once we have a consensus on it), so that most selection issues/features are done in 0.6.0

**Comment by IndrajeetPatil** [comment]
Okay, sounds good!

**Comment by IndrajeetPatil** [comment]
@strengejacke Do you have anything else that you would want to be part of the `0.6` release?

If not, I will submit the update tomorrow.

**Comment by strengejacke** [comment]
No, not necessarily. If there's no hurry, I would probably wait until next week, so we can test the latest changes for some days in "real life" while working with the package, also because the last update is just 4 weeks or fewer ago.

**Comment by IndrajeetPatil** [comment]
I want to hurry because I want the JOSS reviewers to review the package version `0.6`, and not `0.5`.

**Comment by strengejacke** [comment]
ok, but is this a problem? They're reviewing the GitHub-repo anyway (and not CRAN version), no matter which version. And we could then include the updated citation in the next CRAN submission.

**Comment by etiennebacher** [comment]
I'd like to finish #263 as well, so that users have a reference for selecting possibilities after all these changes/new features. I should be able to finish it today or tomorrow (but if you want to do it, go ahead).

**Comment by IndrajeetPatil** [comment]
Take your time. I think I will submit this next week then. That should be enough time to sleep on the recent changes we have made.

**Comment by IndrajeetPatil** [comment]
revdepcheck looks okay: https://github.com/easystats/datawizard/commit/cd8073db301b82fdb38dfad0e0ad9880aaade726

**Comment by strengejacke** [comment]
> revdepcheck looks okay: [cd8073d](https://github.com/easystats/datawizard/commit/cd8073db301b82fdb38dfad0e0ad9880aaade726)

That's a good start ;-)
