### ISSUE TITLE
Test failures with dev tidyselect

### ISSUE THREAD

**Issue by hadley** [easystats/datawizard#267]
I see these failures with dev tidyselect:

```
Failure (test-get_columns.R:273:3): get_columns from other functions
test_fun1(iris, starts_with("Sep")) (`actual`) not equal to iris[c("Sepal.Length", "Sepal.Width")] (`expected`).

`actual` is length 3
`expected` is length 2

`names(actual)`:   "Sepal.Width"  "Petal.Width" "Species"
`names(expected)`: "Sepal.Length" "Sepal.Width"          

`actual$Petal.Width` is a double vector (0.2, 0.2, 0.2, 0.2, 0.2, ...)
`expected$Petal.Width` is absent

`actual$Species` is an S3 object of class <factor>, an integer vector
`expected$Species` is absent

`actual$Sepal.Length` is absent
`expected$Sepal.Length` is a double vector (5.1, 4.9, 4.7, 4.6, 5, ...)

Failure (test-find_columns.R:87:3): find_columns from other functions
test_fun1(iris, starts_with("Sep")) (`actual`) not equal to c("Sepal.Length", "Sepal.Width") (`expected`).

`actual`:   "Sepal.Width"  "Petal.Width" "Species"
`expected`: "Sepal.Length" "Sepal.Width"          
```

Unfortunately I can't reproduce them when running them outside of the full test suite, and the code in `.select_nse()` is rather dense. But I'm happy to help more if you can produce a simple reprex

**Comment by strengejacke** [comment]
@etiennebacher I'm not sure but I _think_ the part that causes this error starts here:
https://github.com/easystats/datawizard/blob/a5e3caa9ed1290b1d6cc3c992ecac30d3dedf6ac/R/select_helpers.R#L121

I've currently no idea why this fails, i.e. which changes in _tidyselect_ may cause these issues.

**Comment by etiennebacher** [comment]
I know why there's this bug, I'll PR soon

**Comment by hadley** [comment]
How do the  `.select.nse` semantics differ from `select()`? You might be able to make this code substantially simpler.

**Comment by etiennebacher** [comment]
@hadley [This vignette](https://easystats.github.io/datawizard/articles/selection_syntax.html) shows all the ways to select variables, but here's a quick summary:
* quoted variable names, e.g `select = c("var1")`
* unquoted variable names, e.g `select = var1`
* positions, e.g `select = 1:3`
* functions, e.g `select = is.numeric`
* formulas (not really useful anymore but kept for backward compat) e.g `select = ~  var1 + var2`
* patterns, e.g `select = starts_with("foo")` (`starts_with()` is detected internally and not an exported function to avoid conflicts with `tidyselect`).

We can also add a minus sign "-" in front of the selection to revert the selection, or use the argument `exclude` that takes the same inputs as `select`.

Some complexity also comes from obtaining the value of objects that are passed to `select` (see [this section](https://easystats.github.io/datawizard/articles/selection_syntax.html#programming-with-selections)). It would be great to simplify `.select_nse()` if you have some ideas of how to do it.

**Comment by hadley** [comment]
Ah ok, that "Programming with selections" technique makes me understand what you're aiming for. It feels like you're trying to magic explicit unquoting away, which we don't believe is possible (you will always end up with edge cases that cause problems).

**Comment by etiennebacher** [comment]
Yes we already noticed that it doesn't work with nested functions (see [this example](https://easystats.github.io/datawizard/reference/find_columns.html#details) in the docs). It is quite tricky to cover all these selections possibilities so there might be more problematic cases. If you have some of these cases in mind, please let us know.

**Comment by hadley** [comment]
Unfortunately I think what you’re trying to do is impossible — there will always be edge cases.
