### ISSUE TITLE
Do not make a new release yet

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#296]
@IndrajeetPatil For information, I need to spend more time on the rewriting of the reshape functions as I discover new corner cases, so I think it would be good to let more time before the next release.

**Comment by IndrajeetPatil** [comment]
Fine by me, except we have to meet the 2022-10-27 deadline for #289.

**Comment by etiennebacher** [comment]
ah right, I forgot this one

**Comment by etiennebacher** [comment]
Ok. Otherwise is it possible to make a branch that just has the fix for R-devel? I'll try to finish my checks for the reshape functions soon

**Comment by IndrajeetPatil** [comment]
Submitted a new release, but currently it's stuck because of this `NOTE` in R CMD check 🤦‍♂️

>  Possibly misspelled words in DESCRIPTION:
>     Patil (29:17)
