### ISSUE TITLE
Fix vignette build failures in no suggests mode

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#299]
We do evaluate these conditionally, so need to figure out why these failures happen.

https://github.com/easystats/datawizard/actions/runs/3283100196/jobs/5407384581

**Comment by etiennebacher** [comment]
The vignette issue is solved but now there are problems in examples that require `bayestestR` (e.g `describe_distribution()`) and in tests because sometimes we load packages at the beginning of tests scripts.
