### ISSUE TITLE
Pulling functions from {effectsize}

### ISSUE THREAD

**Issue by mattansb** [easystats/datawizard#3]
Some ideas:

- [x] `standardize()` + `unstandardize()` (with the `.numeric()`, `.factor()`, `.data.frame()`, `.grouped_df()` methods)
     The method for models (`.default()`) can live in {effectsize} - **meaning datawizard would be imported by effectsize**.
- [x] `change_scale()`
- [x] `normalize()`
- [x] `ranktransform()`
- [x] `adjust()` / `data_adjust()` (*which isn't even used by {effectsize}*)

**Comment by DominiqueMakowski** [comment]
> meaning datawizard would be imported by effectsize

I suspect datawizard will be the new base level for all easystats package as it will definitely be helpful throughout the whole verse

**Comment by IndrajeetPatil** [comment]
Done! 

Moved both functions and relevant tests.

We can make the API more consistent once all functions are in.

**Comment by mattansb** [comment]
But did not remove yet from effectsize, right?

**Comment by IndrajeetPatil** [comment]
Nope.

All functions will be removed from their respective home packages **only after** `datawizard` is on CRAN.
