### ISSUE TITLE
Undo suboptimal formatting for `data_match.R` file

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#341]
This was deliberate on my part (https://github.com/easystats/datawizard/commit/bb42d9fca319380ec4cdc8701a916c30be4788f8). See my commit message for more details.

**Comment by etiennebacher** [comment]
The two `styler` issues you link to are closed and I have the latest `r-lib/styler` but the formatting problem is still there.

Before styling:
```r
#' my_filter <- function(data, variable) {
#'   data_filter(data, {variable} <= 20)
#' }
```
After `styler::style_file("R/data_match.R")`:
```r
#' my_filter <- function(data, variable) {
#'   data_filter(data, {
#'     variable
#'   } <= 20)
#' }
```

**Comment by etiennebacher** [comment]
Or do I need to put `# styler: off` at the top of the file?

**Comment by strengejacke** [comment]
> why we don't want braces to be on separate lines

It's no code block/chunk, it's a kind of "macro" or "shortcut". Thus, it's semantically not comparable to braces around code chunks.

**Comment by IndrajeetPatil** [comment]
As far as the R parser goes, they are exactly the same:

``` r
library(lobstr)

ast(data_filter(data, { condition }))
#> █─data_filter 
#> ├─data 
#> └─█─`{` 
#>   └─condition

ast(data_filter(data, {
  condition
}))
#> █─data_filter 
#> ├─data 
#> └─█─`{` 
#>   └─condition
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

---

Also, how are you going to tell every R user who uses `{styler}` to not do this? 
The tidyverse style guide dictates that the opening and closing braces should be on separate lines.

So the following

```r
data_filter(data, { condition })
```

will always be styled to

```r
data_filter(data, {
  condition
})
```

It doesn't matter whether you think this is a short-cut or a scope or something else.

**Comment by etiennebacher** [comment]
Yes it works fine on separate lines, but to me this feature was more to provide a sort of  `{glue}`-like syntax. 

This seems more familiar to me:
```r
my_filter <- function(data, variable) {
  data_filter(data, {variable} <= 20)
}
my_filter(mtcars, "mpg")
```
than this:
```r
my_filter <- function(data, variable) {
  data_filter(data, {
    variable
  } <= 20)
}
my_filter(mtcars, "mpg")
```

**Comment by IndrajeetPatil** [comment]
That might be so. And a user might indeed write it like `{ condition }`, but `{styler}` is not going to preserve this until the code is stylerignored, which not a lot of users know about. So, I think, we need to make our peace with this formatting. 

I will see if we can preserve our preferred formatting only in Roxygen examples.

**Comment by IndrajeetPatil** [comment]
Yes, styler will not change this:

``` r
library(styler)

style_text('data_filter(data, "{variable} <= 20")')
#> data_filter(data, "{variable} <= 20")
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think that's the way to go then, at least in the docs. Feel free to make this change.

**Comment by strengejacke** [comment]
See interpolating arguments section:
https://tidyselect.r-lib.org/articles/tidyselect.html

I would vote for unquoted braces in one line, this is the most concrete example.

**Comment by strengejacke** [comment]
```
# Interpolating a named argument with {{ }}
toupper_arg <- function(data, arg) {
  sel <- dplyr::select(data, {{ arg }})
  rlang::set_names(sel, toupper)
}
```

**Comment by IndrajeetPatil** [comment]
`{styler}` handles the embrace operator (`{{`) differently than a single brace (`{`), which signals the start of a scope.

``` r
library(styler)

style_text("{{ x }}")
#> {{ x }}

style_text("{ x }")
#> {
#>   x
#> }
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
But the idea is the same. The `{}` have different meanings in different contexts, thus they should be treated (i.e. styled) differently.

**Comment by IndrajeetPatil** [comment]
You can create a feature request in `{styler}` repo and see if this can be supported: https://github.com/r-lib/styler/issues

**Comment by strengejacke** [comment]
I tried disabling styler in the docs, let's see if this helps
