### ISSUE TITLE
An error in Multilevel

### ISSUE THREAD

**Issue by teindor** [easystats/datawizard#366]
Hello,
I tried using this simple code for multilevel correlation:
wf %>%  correlation(select = "inflated", select2 = "gender",multilevel = TRUE)
The factor name is "id". I'm getting an error:
Error: No random effects terms specified in the formula

I tried different things like wf %>% group_by(id)  %>% correlation(select = "inflated", select2 = "gender",multilevel = TRUE)
or wf %>%  correlation(select = "inflated", select2 = "gender",multilevel = TRUE, formula = inflated ~ gender + (1|id)) without help. I can't find any help in the documents. 
Any ideas?
[wf.csv](https://github.com/easystats/datawizard/files/10812766/wf.csv)

**Comment by etiennebacher** [comment]
Reprex:
``` r
library(correlation)
packageVersion("correlation")
#> [1] '0.8.3'

test <- data.frame(
  gender = c(NA, 1L, 1L, 1L, NA, 1L, 0L, 1L, 0L, NA),
  inflated = c(3, 2.125, 3.5, 4.625, 2.875, 3.25, 2, 2.75, 2.875, 3.125)
) 

test |> 
  correlation(select = "inflated", select2 = "gender", multilevel = TRUE)
#> Error: No random effects terms specified in formula
```
