### ISSUE TITLE
CRAN failures

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#390]
"Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_datawizard.html>.

Please correct before 2023-04-06 to safely retain your package on CRAN.

There is a check service for M1mac issues: see
https://www.stats.ox.ac.uk/pub/bdr/M1mac/README.txt .
However, it is running a much older version of the OS
and toolchain.

The CRAN Team"

**Comment by strengejacke** [comment]
Some are different at position 1e-1 or 1e-2, so I'm not sure your tolerance is not still too strict.

**Comment by IndrajeetPatil** [comment]
I have M1 Mac and can confirm that the fix works.

**Comment by etiennebacher** [comment]
Seems like there are still the same failures

"
package datawizard_0.7.1.tar.gz has been auto-processed.
The auto-check found additional issues for the *last* version released on CRAN:
  M1mac <https://www.stats.ox.ac.uk/pub/bdr/M1mac/datawizard.out>
  noLD <https://www.stats.ox.ac.uk/pub/bdr/noLD/datawizard.out>
CRAN incoming checks do not test for these additional issues.
Hence please reply-all and explain: Have these been fixed?

Log dir: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.7.1_20230329_092941/>
The files will be removed after roughly 7 days.
Installation time in seconds: 34
Check time in seconds: 270
R version 4.3.0 alpha (2023-03-28 r84109 ucrt)

Pretests results:
Windows: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.7.1_20230329_092941/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.7.1_20230329_092941/Debian/00check.log>
Status: OK"

Why do we still have these??
