### ISSUE TITLE
`weighted` functions should better deal with `NA` values.

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#394]
Currently, there's no possibility to clean the variable and weights from `NA`s in _datawizard_ functions. I think we should to pairwise deletion of cases with missing value, so we have only complete cases left, and then compute the weighted statistic - as default behaviour.

``` r
x <- c(1, 2, 3, NA, 4)
w <- c(1, NA, 0.5, 0.8, 1.2)

# current behaviour
datawizard::weighted_mean(x, w)
#> [1] NA
# desired behaviour
report:::.weighted_mean(x, w)
#> [1] 2.703704

# current behaviour
datawizard::weighted_median(x, w)
#> [1] 3
# desired behaviour
report:::.weighted_median(x, w)
#> [1] 3

# current behaviour
datawizard::weighted_sd(x, w)
#> [1] NA
# desired behaviour
report:::.weighted_sd(x, w)
#> [1] 1.708622
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
Can't we just move these internal functions from `report` here since they already work?

**Comment by strengejacke** [comment]
Yes, we could do that. Only applies to SD and mean, but - I think we had this discussion before - for some reason, weighted SD is different in both packages:

``` r
x <- c(1, 2, 3, 2, 4)
w <- c(1, 0.7, 0.5, 0.8, 1.2)

datawizard::weighted_sd(x, w)
#> [1] 1.285846
report:::.weighted_sd(x, w)
#> [1] 1.303898

datawizard::weighted_mean(x, w)
#> [1] 2.452381
report:::.weighted_mean(x, w)
#> [1] 2.452381

datawizard::weighted_median(x, w)
#> [1] 2
report:::.weighted_median(x, w)
#> [1] 2
```

<sup>Created on 2023-04-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Or you simply add this code from `weighted_median()` to the other functions:

```r
  # remove missings
  x[is.na(weights)] <- NA
  weights[is.na(x)] <- NA

  weights <- stats::na.omit(weights)
  x <- stats::na.omit(x)
```

**Comment by mattansb** [comment]
`datawizard::weighted_sd()` uses the same code as `stats::cov.wt()`. Not sure what {report} is doing.
