### ISSUE TITLE
Fix order dependency in unit tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#396]
cf. https://github.com/easystats/easystats/issues/358

**Comment by etiennebacher** [comment]
Cause: when `dplyr` is in the environment, when we have a `grouped_df` and we call `[` on it (basically any time we apply a function on grouped data), `dplyr::[.grouped_df` will add some tibble attributes:
``` r
library(datawizard)
x <- data.frame(a = c(1, 2), b = c(3, 4)) |> 
  data_group(a)
class(x[1, ])
#> [1] "grouped_df" "data.frame"

suppressPackageStartupMessages(library(dplyr))

class(x[1, ])
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"
```

Therefore, depending on whether this method from `dplyr` is accessible, the expected output changes. Once again, it comes from some "leaking" between `test_that()` calls. One solution is to remove the expectations on the class of output.

**Comment by mattansb** [comment]
We should stop *loading* packages in tests.
`pkg::foo()` instead of `require(pkg)` to use `foo()`.

**Comment by etiennebacher** [comment]
@mattansb it wouldn't solve the problem:

``` r
library(testthat)

test_that("foo 1", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] FALSE
#> ── Skip (???): foo 1 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 2", {
  print(insight::get_parameters)
})
#> function (x, ...) 
#> {
#>     UseMethod("get_parameters")
#> }
#> <bytecode: 0x000001fa50180e60>
#> <environment: namespace:insight>
#> ── Skip (???): foo 2 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 3", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] TRUE
#> ── Skip (???): foo 3 ───────────────────────────────────────────────────────────
#> Reason: empty test
```

**Comment by IndrajeetPatil** [comment]
Namespacing the package also loads the namespace for that package. E.g. if you look at the session info here, you will see that `{MASS}` is also the search path, although I didn't do `library(MASS)`.

``` r
invisible(MASS::rlm)
"MASS" %in% loadedNamespaces()
#> [1] TRUE
```

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So, as Etienne shows in his comment, even if we use namespace syntax to access a function from a certain package in one test, that namespace leaks into other tests.
