### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#4]
A list of questions:

- NSE, characters or both? It's likely that for we will need to plan something like a super robust `data_select()` that can accommodate various types of inputs (+ regex etc.). This will also be very useful in other easystats packages.
- Naming scheme:
  - column names: cols? vars? colnames? 
  - row names: rows? rownames? 
  - ...
- Regarding pattern-matching, follow tidyverse's API (`starts_with`, `ends_with`, `matches`) or raw regex? Or somewhat in between with a few commonly-used regex helpers (`rgx_start`, `rgx_end`, `rgx_digits`, ..., [tho obviously not to the extent of RVerbalExpressions](https://github.com/VerbalExpressions/RVerbalExpressions))

**Comment by bwiernik** [comment]
Question: Why do we need `data_select()` when `base::subset()` exists? Same for `mutate()`:`transform()`.
`

**Comment by bwiernik** [comment]
Re: NSE, it causes problems with a lot of CRAN checks (e.g., that is why the `rlang::.data` pronoun exists). In my experience teaching R and tidyverse, I think would honestly could go either way. Some students really like NSE, but other get tripped up on when you need quotes versus not. It isn't too terrible to do NSE with just base stuff.

**Comment by bwiernik** [comment]
Re: pattern-matching, let's port over the `string_*` helpers from sjmisc and add `col_*` versions that are analogous to `tidyselect::starts_with()`, etc. in evaluating the patterns against the column names of the data.

**Comment by strengejacke** [comment]
> Why do we need `data_select()` when `base::subset()`

One really annoying aspect of many base R functions is that they drop attributes, which is really sad when working with labelled data.

Re NSE: I'd say we could support both, so it's easy for users and developers:

``` r
subset(iris, select = "Species") |> head()
#>   Species
#> 1  setosa
#> 2  setosa
#> 3  setosa
#> 4  setosa
#> 5  setosa
#> 6  setosa
subset(iris, select = Species) |> head()
#>   Species
#> 1  setosa
#> 2  setosa
#> 3  setosa
#> 4  setosa
#> 5  setosa
#> 6  setosa
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
And here's my base-R function to evaluate dots, similar to `dplyr::select()` et al.
https://github.com/strengejacke/sjlabelled/blob/master/R/utils_get_dots.R

**Comment by DominiqueMakowski** [comment]
data_select was a very first draft meant to be a helper to select/retrieve columns with more flexible inputs such as characters (default), regex patterns etc. Our version of `dplyr::select` if you will.

(btw @IndrajeetPatil I think here you could put all the `data_*`/ `text_*` functions in separate files with their own documentation page rather than the same one)

**Comment by bwiernik** [comment]
Let's use `string_*` as our prefix versus `text_*` I think.

**Comment by DominiqueMakowski** [comment]
any particular reasons?

**Comment by bwiernik** [comment]
"string" or "character" are used throughout R to refer to string data. It's a terminology users should know, and I think there is value in being consistent with, eg, stringr.

**Comment by strengejacke** [comment]
I think we can close this, and open new issues whenever we stumble upon any inconsistencies...
