### ISSUE TITLE
data_select(): add option to evaluate a function passed to `select`

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#407]
Trying to fix a bug in modelbased: but it basically fails because the function is not evaluated:

``` r
model <- lm(Petal.Length ~ Petal.Width, data=iris)
datawizard::data_select(iris, insight::find_predictors(model, effects = "fixed", flatten = TRUE))
#> Error in switch(type, `:` = .select_seq(x, data, ignore_case, regex, verbose), : EXPR must be a length 1 vector
```

<sup>Created on 2023-04-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I understand the need to catch unevaluated function calls (for stuff like `as.numeric` to work), but we should either come up with a smarter to know when to evaluate vs. not, or add an argument `force_eval` or something to force it to evaluate

**Comment by etiennebacher** [comment]
You can evaluate the function beforehand and use its output:

``` r
library(datawizard)

model <- lm(Petal.Length ~ Petal.Width, data=iris)

cols <- insight::find_predictors(model, effects = "fixed", flatten = TRUE)

head(data_select(iris, cols))
#>   Petal.Width
#> 1         0.2
#> 2         0.2
#> 3         0.2
#> 4         0.2
#> 5         0.2
#> 6         0.4
```

**Comment by etiennebacher** [comment]
Also, in this case it would be easy but if you want to do this in a custom function then evaluating can be tricky:

```r
foo <- function(effects) {
  data_select(iris, insight::find_predictors(model, effects = i, flatten = TRUE))
}
```
Evaluating `insight::find_predictors(model, effects = i, flatten = TRUE)` would error because we need to get `i` first

**Comment by DominiqueMakowski** [comment]
or maybe a safeguard, like try to running the caught function on the data (as it is primarily expected) and if it fails try to run the expression on its own and if it fails again then throw an error

**Comment by etiennebacher** [comment]
@strengejacke @IndrajeetPatil what do you think?

**Comment by strengejacke** [comment]
#407 _should_ fix this issue.
