### ISSUE TITLE
`remove_na` vs. `na.rm`

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#412]
We currently mix both argument names, `remove_na` vs. `na.rm`. I suggest we decide on one and deprecate the other one.

**Comment by etiennebacher** [comment]
I'd say we go with `na.rm` which is standard in other functions (`mean()`, `sum()`, etc.)

**Comment by strengejacke** [comment]
I was just going for `remove_na`, since this is more compliant with our [code style conventions](https://easystats.github.io/easystats/articles/conventions.html)... 😬  but it's easy to do a global find/replace.

**Comment by etiennebacher** [comment]
True, now I don't know which one I prefer

**Comment by etiennebacher** [comment]
Sidenote: this might lead to breaking changes in other *easystats* packages

**Comment by strengejacke** [comment]
Yes, I would also keep the `na.rm` for now and softly deprecate it.

**Comment by etiennebacher** [comment]
Would `na_rm` be a possible alternative? It's closer to `na.rm` and I think I already saw it somewhere but can't remember in which package exactly
