### ISSUE TITLE
Add select helpers to `data_to_wide` and friends

### ISSUE THREAD

**Issue by rempsyc** [easystats/datawizard#416]
I am currently trying to use `datawizard::data_to_wide()` in another PR but it seems like it is throwing an error because of differing number of rows, which seems cannot be fixed by specifying columns to be selected because the argument has not been implemented for those functions so far. Reprex:

``` r
datawizard::data_to_wide(
  iris,
  values_from = "Sepal.Length",
  names_from = "Species",
  select = c("Sepal.Length", "Species")
)
#> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 147, 145, 144
```

<sup>Created on 2023-05-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The workaround is to run `datawizard::data_select()` on the data frame before hand, but it would be nice if it was integrated.

**Comment by etiennebacher** [comment]
There's no arg `select` in `data_to_wide()` because this argument doesn't exist in `tidyr::pivot_wider()`, that we try to mimick. Specifying `select` doesn't change anything because it is passed in `...` and these aren't used anywhere.

Using `tidyr::pivot_wider()` with your query would return list-columns:

``` r
tidyr::pivot_wider(
  iris,
  values_from = "Sepal.Length",
  names_from = "Species"
)
#> Warning: Values from `Sepal.Length` are not uniquely identified; output will contain
#> list-cols.
#> • Use `values_fn = list` to suppress this warning.
#> • Use `values_fn = {summary_fun}` to summarise duplicates.
#> • Use the following dplyr code to identify duplicates.
#>   {data} %>%
#>   dplyr::group_by(Sepal.Width, Petal.Length, Petal.Width, Species) %>%
#>   dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
#>   dplyr::filter(n > 1L)
#> # A tibble: 143 × 6
#>    Sepal.Width Petal.Length Petal.Width setosa    versicolor virginica
#>          <dbl>        <dbl>       <dbl> <list>    <list>     <list>   
#>  1         3.5          1.4         0.2 <dbl [1]> <NULL>     <NULL>   
#>  2         3            1.4         0.2 <dbl [1]> <NULL>     <NULL>   
#>  3         3.2          1.3         0.2 <dbl [2]> <NULL>     <NULL>   
#>  4         3.1          1.5         0.2 <dbl [2]> <NULL>     <NULL>   
#>  5         3.6          1.4         0.2 <dbl [1]> <NULL>     <NULL>   
#>  6         3.9          1.7         0.4 <dbl [1]> <NULL>     <NULL>   
#>  7         3.4          1.4         0.3 <dbl [1]> <NULL>     <NULL>   
#>  8         3.4          1.5         0.2 <dbl [2]> <NULL>     <NULL>   
#>  9         2.9          1.4         0.2 <dbl [1]> <NULL>     <NULL>   
#> 10         3.1          1.5         0.1 <dbl [1]> <NULL>     <NULL>   
#> # ℹ 133 more rows
```

This is not implemented yet in `data_to_wide()` but is it really what you want?

**Comment by rempsyc** [comment]
I see, thanks for the explanation, that makes sense. I think I was on the wrong track with attempting to pivot wider.

Essentially, I was simply trying to get one column per group for a given variable, like this:

``` r
x <- datawizard::data_select(iris, c("Sepal.Length", "Species"))
list.dat <- lapply(seq_len(3), function(i) {
  index <- which(x$Species == as.character(unique(x$Species)[i]))
  y <- datawizard::data_filter(x, index)
  names(y)[1] <- as.character(unique(x$Species)[i])
  y <- y[1]
})
head(do.call(cbind, list.dat))
#>   setosa versicolor virginica
#> 1    5.1        7.0       6.3
#> 2    4.9        6.4       5.8
#> 3    4.7        6.9       7.1
#> 4    4.6        5.5       6.3
#> 5    5.0        6.5       6.5
#> 6    5.4        5.7       7.6
```

<sup>Created on 2023-05-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm sure there's a simpler way to do this lol. Do you know the datawizard way to get there? :P

**Comment by etiennebacher** [comment]
If you're ok with `poorman`, that would work:

``` r
suppressPackageStartupMessages({
  library(poorman)
  library(datawizard)
})

x <- data_select(iris, c("Sepal.Length", "Species"))

x |> 
  group_by(Species) |>
  mutate(
    id = 1:n()
  ) |> 
  ungroup() |> 
  data_to_wide(
    id_cols = "id",
    names_from = "Species",
    values_from = "Sepal.Length"
  ) |> 
  head()
#>   id setosa versicolor virginica
#> 1  1    5.1        7.0       6.3
#> 2  2    4.9        6.4       5.8
#> 3  3    4.7        6.9       7.1
#> 4  4    4.6        5.5       6.3
#> 5  5    5.0        6.5       6.5
#> 6  6    5.4        5.7       7.6
```
We only need `poorman` to create the `id` in the pipe workflow. I think we should implement a function `rowid_as_column()` that would mimic `tibble::rowid_to_column()` (we already have `rownames_as_column()` but doesn't work with row numbers).

With `rowid_as_column()` we should be able to do:
```r
x |> 
  data_group(Species) |> 
  rowid_as_column() |> 
  ungroup() |> 
  data_to_wide(
    id_cols = "id",
    names_from = "Species",
    values_from = "Sepal.Length"
  )
```
I can implement this a bit later (but feel free to do it if you want)

**Comment by rempsyc** [comment]
Thanks for taking care of this @etiennebacher !

Since this is for easystats internal use I wanted not to rely on `poorman`. However, I see that I was simply missing the id variable... damn, so simple haha. I could have done it manually too no? Oh actually no... I see what you did, it has to be the same id that is repeated, not `1:nrow(x)`...

So the manual way to do it would have been...

``` r
library(datawizard)

x <- data_select(iris, c("Sepal.Length", "Species"))

x$id <- seq_len(nrow(x)/length(levels(x$Species)))

x |> 
  data_to_wide(
    id_cols = "id",
    names_from = "Species",
    values_from = "Sepal.Length"
    ) |> 
  head()
#>   id setosa versicolor virginica
#> 1  1    5.1        7.0       6.3
#> 2  2    4.9        6.4       5.8
#> 3  3    4.7        6.9       7.1
#> 4  4    4.6        5.5       6.3
#> 5  5    5.0        6.5       6.5
#> 6  6    5.4        5.7       7.6
```

<sup>Created on 2023-05-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

However, a limitation of this approach seems to be that it requires an equal n in each group... so that would not work in all cases for contrasts when there are unequal groups anyway. Correction: with my manual approach, unequal groups doesn't work, but with the `poorman` approach you suggested, unequal group works and then it is just filled with `NA`, interesting.

**Comment by etiennebacher** [comment]
Looks like it works with the code in #417:

``` r
library(datawizard)

x <- data_select(iris, c("Sepal.Length", "Species")) |> 
  data_group(Species) |>
  rowid_as_column("id") |> 
  data_ungroup()

x <- head(x, -1)

x |> 
  data_to_wide(
    id_cols = "id",
    names_from = "Species",
    values_from = "Sepal.Length"
  ) |> 
  tail()
#>    id setosa versicolor virginica
#> 45 45    5.1        5.6       6.7
#> 46 46    4.8        5.7       6.7
#> 47 47    5.1        5.7       6.3
#> 48 48    4.6        6.2       6.5
#> 49 49    5.3        5.1       6.2
#> 50 50    5.0        5.7        NA
```

**Comment by rempsyc** [comment]
Jolly good then! Given it seems inconsistent in `tidyr`, I don't expect more from our own version. They're showing similar behaviour right now so that's great. Thanks!
