### ISSUE TITLE
Plots for describe_distribution() and data_tabulate()

### ISSUE THREAD

**Issue by jmgirard** [easystats/datawizard#419]
While teaching, it would be very handy to have a quick way to visualize distributions. I was thinking this could either be accomplished using S3 methods (Option 1) or an argument (Option 2) for the `describe_distribution()` and `data_tabulate()` functions.

``` r
library(ggplot2)
library(datawizard)

# Describe Distribution

## Desired input
dd <- describe_distribution(mpg, select = c("hwy", "cty"))
### Option 1: plot(dd)
### Option 2: describe_distribution(mpg, select = c("hwy", "cty"), plot = TRUE)

## Desired output
mpg |> 
  data_select(select = c("hwy", "cty")) |> 
  data_to_long() |> 
  ggplot(aes(x = value)) +
  facet_wrap(~name, scales = "free") +
  geom_histogram(bins = 30)
```

![](https://i.imgur.com/DAijGUm.png)

``` r

# Data Tabulate

## Desired input
dt <- data_tabulate(mpg, select = c("cyl", "drv"))
### Option 1: plot(dt)
### Option 2: data_tabulate(mpg, select = c("cyl", "drv"), plot = TRUE)

## Desired output
mpg |> 
  data_select(select = c("cyl", "drv")) |> 
  data_to_long() |> 
  ggplot(aes(x = value)) +
  facet_wrap(~name, scales = "free") +
  geom_bar()
```

![](https://i.imgur.com/Zp1CJsU.png)

<sup>Created on 2023-05-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
`describe_distribution()` has [`plot()`-methods](https://easystats.github.io/see/articles/parameters.html#description-of-variable-distributions). But for `data_tabulate()`, there's indeed no plot-method yet.

**Comment by jmgirard** [comment]
Hmm... I must just be running into a different problem.

``` r
library(ggplot2)
library(datawizard)

x1 <- describe_distribution(mpg$drv)
plot(x1)
```

![image](https://github.com/easystats/datawizard/assets/6829033/df6d5a52-3a1b-43f4-9454-413732bf3c24)


``` r

x2 <- describe_distribution(mpg, select = "drv")
#> Error in class(out) <- unique(c("parameters_distribution", "see_parameters_distribution", : attempt to set an attribute on NULL
plot(x2)
#> Error in eval(expr, envir, enclos): object 'x2' not found
```

<sup>Created on 2023-05-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
@jmgirard there are several issues here:

* plotting method for `data_tabulate()`
* error with the plot method when using `describe_distribution()` with `select`
* error with `describe_distribution()` with a character column

so I close this issue but I'll open three different ones to tackle each problem separately
