### ISSUE TITLE
Release checklist for 0.8.0

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#429]
- [x] #428 
- [ ] #415 
- [x] #426 
- [x] maybe also #423

@strengejacke

**Comment by strengejacke** [comment]
Would you like to finish the work on #415, or is this something that can be done later? In other words: when do you plan to submit _datawizard_?

**Comment by etiennebacher** [comment]
I won't have time and actually I received an email today about a possible incoming CRAN failure due to a change in R-devel (which is why I pushed 9b2e2b5).

I'll try to submit by the end of the week
