### ISSUE TITLE
Rename `rowmean_n()`?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#447]
From @IndrajeetPatil's comment: https://github.com/easystats/datawizard/commit/6e3182c7eb9602badffb5db94cf3cea8149c193d#commitcomment-124303628

> Sorry, I didn't get to weigh in before, but I personally find the function name very dissatisfying, and even a bit misleading. I think the name should make a reference to the fact that this is relevant for missing values. I know that n is mandatory, and so users may figure it out once they use it mistakenly.
>
> How about renaming it to `rowmean_n_missing()`?

@strengejacke

**Comment by etiennebacher** [comment]
On the other hand, if you see `rowmean_n()` for the first time, what do you think the `n` stand for? 

`rowmean_n_missing()` is also a bit misleading IMO because `n` actually refers to the minimal number of non-missing values required to compute the mean.

**Comment by etiennebacher** [comment]
I guess if I were a user discovering this function:

* `rowmean_n()` -> hard to know that it does because I don't know what the n stands for, so need to check the docs 
* `rowmean_n_missing()` -> this function computes the rowmean if there are `n` or more missing values (while it's the opposite)

**Comment by IndrajeetPatil** [comment]
When I read that name, my first hunch is that it's going to calculate rowwise mean for the first _n_ rows.

**Comment by strengejacke** [comment]
I don't think there is a perfect name for this function, but `rowmean_n_missing()` looks very cryptic to me.

**Comment by strengejacke** [comment]
See also https://r4stats.com/2014/09/03/adding-the-spss-mean-n-function-to-r/

**Comment by DominiqueMakowski** [comment]
Shouldn't it be easier with just a homemade version of `row_mean()` with some select/exclude sugar and an`max_missing` argument?

**Comment by strengejacke** [comment]
That sounds good!

**Comment by strengejacke** [comment]
`max_missing` or `min_valid`? I'm used to think in minimum amount of valid values...
