### ISSUE TITLE
Why not execute `contrs()` example?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#461]
Currently, we are skipping its evaluation and hardcoding its output into the docs, which is rarely a good idea. Is there any reason for this?

https://github.com/easystats/datawizard/blob/ec6a9cec624d13833c7cb5ad3c72ec3d2e0b14d5/R/contrs.R#L35C1-L84

**Comment by etiennebacher** [comment]
I mentioned this when I reviewed the PR but having these comments on the same rows as the output is useful and I had no good alternatives to propose: https://github.com/easystats/datawizard/pull/444#discussion_r1286943542

**Comment by IndrajeetPatil** [comment]
Hmm, I see. 

@mattansb If these comments are so helpful, wouldn't it actually make sense to add another column to the output where these details are included? It will be helpful for everyone, irrespective of whether they look at the examples or not.

**Comment by strengejacke** [comment]
> wouldn't it actually make sense to add another column to the output

contrasts and solve return a matrix, so you cannot add that column to the output.

**Comment by strengejacke** [comment]
And that function is based on `stats::contr.treatment()`, I don't think the output will ever change, thus I don't see a problem hard coding the example here.

**Comment by IndrajeetPatil** [comment]
I have an idea how to make everyone happy here. Will make a commit.
