### ISSUE TITLE
Test failure due to `Matrix` update

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#471]
There's one failure in the tests and in examples due to an update of `Matrix`: 

```r
Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix'
```

~Strangely this only fails in the `oldrel-3` on Ubuntu but I can reproduce on Windows with R 4.3.2~ (Edit: works after reinstalling `lme4` from source locally)

StackOverflow solution: https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack

@strengejacke @IndrajeetPatil I'm not super familiar with the tricks about reinstalling `Matrix` and its dependencies from source. Do you know where this should be fixed?

**Comment by IndrajeetPatil** [comment]
I had updated the workflows to install the respective packages from source and also invalidated the cache for a good measure. And yet that hasn't resolved this issue on some R versions.

I have no idea why this hasn't resolved the issue for all R versions.

**Comment by IndrajeetPatil** [comment]
Relevant commits: https://github.com/easystats/workflows/commit/285309f9bcb710fc47a7e08a074062c6f9958043, https://github.com/easystats/workflows/commit/3df7fc19d293b6a59db84541e578887731856b49, https://github.com/easystats/workflows/commit/7c59a2eebc702421bb0b4425042a964dc12417f2

Let me know if you have any other ideas.

**Comment by etiennebacher** [comment]
Should we reinstall `lme4` from source too? That's what was suggested on SO and it worked locally

**Comment by IndrajeetPatil** [comment]
I had also done that for every dependency that `{Matrix}` was linking to in https://github.com/easystats/workflows/commit/9e72247e96040ba5619e925aaa7be761b66d940e, but that somehow still did not work.

We can try it again, though. Maybe things have changed somehow.

**Comment by etiennebacher** [comment]
I don't know then, I'll try again in a few days. If it's supposed to be fixed then maybe this is just a temp bug, especially since it only fails on one of the CI jobs

**Comment by IndrajeetPatil** [comment]
During R package development, I have never experienced the kind of frustration I've experienced since this Matrix update. 
The CI pipelines in all stats-related packages have gone haywire. I really wish CRAN itself would provide some solution when such incompatible changes take place in one of the most important packages.

**Comment by etiennebacher** [comment]
Yes that's super annoying, it also slows down the CI a lot: https://github.com/easystats/workflows/issues/37

**Comment by etiennebacher** [comment]
This is not related to `datawizard` and I think it's a duplicate of https://github.com/easystats/workflows/issues/54 so closing
