### ISSUE TITLE
Segfault on Ubuntu with R-devel 

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#491]
https://github.com/easystats/datawizard/actions/runs/8401987322/job/23010912302#step:8:52

@strengejacke I can try to take a look tomorrow (I don't have an Ubuntu machine right now) but it looks like an issue with `lme4::lmer()`

**Comment by strengejacke** [comment]
Not sure, could also be https://github.com/glmmTMB/glmmTMB/issues/1007#issuecomment-2013810644?

**Comment by IndrajeetPatil** [comment]
Do we need to keep this open? I think the source was some dependency.
