### ISSUE TITLE
winsorize - add a na.rm parameter?

### ISSUE THREAD

**Issue by Cal-Fang** [easystats/datawizard#496]
I am trying to winsorize a column and I notice when I set the threshold value smaller, the right side will not be winsorized. Here I created a random sample [test.csv](https://github.com/easystats/datawizard/files/15098363/test.csv) to replicate the issue and attached an example data file.

```
temp <- write_csv("test.csv")
check <- temp %>% 
  mutate(winsorized_psych = psych::winsor(raw, trim=0.025),
         winsorized_dw = datawizard::winsorize(raw, threshold=0.025))
```

<img width="407" alt="image" src="https://github.com/easystats/datawizard/assets/59776160/a60e35c2-2196-4237-817b-3d4d43721ed3">

Here you can see, that when I use the psych package's winsor() function, these values would be winsorized but not when I use the winsorize() function from the datawizard package.

There are around 200 NA values in this column, which is causing the issue as I would get the desired result if I run:
```
check <- temp %>% 
  drop_na() %>% 
  mutate(winsorized_psych = psych::winsor(raw, trim=0.025),
         winsorized_dw = datawizard::winsorize(raw, threshold=0.025))
```

Is it possible to add a na.rm parameter to the winsorize function in the future?

**Comment by strengejacke** [comment]
Do you have a reproducible example? The following, including NA values, return identical results:

``` r
set.seed(123)
d <- sample(c(1:30, NA), 200, replace = TRUE)
head(cbind(
  as.vector(datawizard::winsorize(d, threshold = 0.025)),
  as.vector(psych::winsor(d, trim=0.025))
))
#>      [,1] [,2]
#> [1,]   NA   NA
#> [2,]   15   15
#> [3,]   19   19
#> [4,]   14   14
#> [5,]    3    3
#> [6,]   10   10
```

<sup>Created on 2024-04-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Even with your data, results are identical:

``` r
d <- datawizard::data_read("c:/Users/Daniel/Downloads/test.csv")
out <- d |> 
  datawizard::data_modify(
    winsorized_psych = psych::winsor(raw, trim = 0.025),
    winsorized_dw = datawizard::winsorize(raw, threshold = 0.025)
  )

head(out, 20)
#>        raw winsorized_psych winsorized_dw
#> 1   866860           866860        866860
#> 2   958064           958064        958064
#> 3   866860           866860        866860
#> 4   958064           958064        958064
#> 5   391008           391008        391008
#> 6   213454           213454        213454
#> 7   256535           256535        256535
#> 8   519263           519263        519263
#> 9   713251           713251        713251
#> 10  405528           405528        405528
#> 11  866860           866860        866860
#> 12  958064           958064        958064
#> 13  232763           232763        232763
#> 14  958064           958064        958064
#> 15  311783           311783        311783
#> 16 1368939          1368939       1368939
#> 17  272016           272016        272016
#> 18  318697           318697        318697
#> 19  409067           409067        409067
#> 20  958064           958064        958064
```

<sup>Created on 2024-04-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
Closing as not reproducible, feel free to reopen if the bug persists on the development version of `datawizard` and you can provide a reproducible example.
