### ISSUE TITLE
list of possible functions to be included in `datawizard`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#5]
Please edit the list as you come across such functions in the core packages. 

I am organizing by core package:

# `bayestestR`

- [x] `simulate_correlation`
- [x] `simulate_difference`
- [x] `simulate_ttest`

# `effectsize`

- [x] `adjust`
- [x]  `standardize`
- [x] `normalize`

# `correlation`

- [x] `simulate_simpson`
- [x] `winsorize`

# `parameters`

- [x] `center`
- [x] `data_partition`
- [x] `data_to_numeric`
- [x] `demean` (?)
- [x] `degroup` (?)
- [x] `reduce_parameters`
- [x] `principal_components()`
- [x] `factor_analysis()`
- [x] `n_factors()`
- [x] `n_clusters()`
- [x] `check_factorstructure()`
- [x] `check_clusterstructure()`

# `performance`

# `modelbased`

# `report`

- [x] `data_rename`
- [x] `data_findcols`
- [x] `data_remove`
- [x] `data_reorder`
- [x] `data_addprefix`
- [x] `data_addsuffix` 

# `insight`

- [x] `check_if_installed`
- [x] `data_to_long`
- [x] `data_to_wide`
- [x] `format_message`
- [ ] All the table printing (possibly the implementation of a generic `easydf`/`easydata` class for dataframe that would be naturally printed with possible methods like `data_add_title` / `data_add_footer` that can be nicely put in a chain

**Comment by DominiqueMakowski** [comment]
(@IndrajeetPatil you added z_fisher from correlation but i don't think it should be moved)

**Comment by IndrajeetPatil** [comment]
Oops, undid that. 

I am just copying for now. We can start evicting these functions from their current homes once `datawizard` is on CRAN.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Can you please update the `modelbased` section? 
I am guessing this list may have changed after your recent massive rewrite of the package?

**Comment by bwiernik** [comment]
Once we move these, do we want to re-export the functions in their old home? I think these are small enough in usage that I'm not worried about breaking changes and would prefer to shed the dependency if possible.

**Comment by IndrajeetPatil** [comment]
> Once we move these, do we want to re-export the functions in their old home?

Hmm, good question. 
I think we can do a revdepcheck once removed from old home and see if this leads to any substantial breakages. If not, it's safe not to re-export them.

**Comment by DominiqueMakowski** [comment]
`report` also has a bunch of very convenient `text_*` function to manipulate text that we should definitely move here, it will help streamlining the easystats code

**Comment by IndrajeetPatil** [comment]
These ones?
https://easystats.github.io/report/reference/format_text.html

**Comment by bwiernik** [comment]
What makes you think those should move @DominiqueMakowski? They seem pretty squarely in the report wheelhouse to me and to have less to do with data than report formatting. Do we need these functions in other easystats packages?

**Comment by DominiqueMakowski** [comment]
yes I think we do format quite a lot of messages / table footers / information that I could see it useful. Moreover it kinda fits with datawizard's scope (assuming text is some form of data that one wants to manipulate) and users could need it. 

Essentially datawizard could take care of all the non-model-related/non-stats stuff

**Comment by mattansb** [comment]
> Essentially datawizard could take care of all the non-model-related/non-stats stuff

Doesn't this include half of insight?

**Comment by strengejacke** [comment]
I'm a bit undecided whether we should move pca/fa from parameters to datawizard.

**Comment by bwiernik** [comment]
Is the purpose of those functions to provide a more consistent and clear API over psych/etc?

**Comment by DominiqueMakowski** [comment]
yeah and also because re-inventing the wheel is our favourite procrastination method 😁

**Comment by DominiqueMakowski** [comment]
> I'm a bit undecided whether we should move pca/fa from parameters to datawizard.

I think both make sense. Because we could argue that PCA/FA is a way to understand the structure in the data, and (especially PCA) and to "simplify" its dimensionality, which is often done before subsequent analysis. In that regards, it is part of "data preparation & transformation", so it would definitely fit in datawizard. Additionally having this type of functions would help distinguish datawizard from other purely data-wrangling packages like poorman or dplyr-tidyr.  

The main drawback I see is the breaking change..

**Comment by bwiernik** [comment]
I would say moving them makes more sense. They have always felt weirdly out of place in performance to me.

**Comment by IndrajeetPatil** [comment]
> The main drawback I see is the breaking change

We can re-export these function from `parameters` to avoid this? 
I know your hesitation when it comes to re-exports, but I think this is a perfect situation where to use them.

**Comment by bwiernik** [comment]
I don't have any strong objection to re-exporting when it makes sense to do so. Just don't think that _all_ of the functions need to be re-exported.

**Comment by IndrajeetPatil** [comment]
> @DominiqueMakowski Can you please update the modelbased section?
I am guessing this list may have changed after your recent massive rewrite of the package?

@DominiqueMakowski *bump*

**Comment by DominiqueMakowski** [comment]
done, both functions are now in insight

**Comment by IndrajeetPatil** [comment]
I have also moved `parameters` functions.

The only thing now remains is printing utilities from `insight`. I'd prefer if @strengejacke moves them.

**Comment by DominiqueMakowski** [comment]
Rather than re-exporting too much and having a mess, I'd say once modelbased and report are on CRAN and this round of update is completed, then we push datawizard to CRAN. Since most of its most-used (and thus sensitive) functions are already relatively stable, we shouldn't worry about having to re-update datawizard in an emergency, so we can safely start depending on it once it is on CRAN. We knew we needed this package for some time and its addition really fills a hole in the verse.

I would even say that we could consider going out of alpha and to beta (0.1.0) for the next round of release, to mark this structural update.

**Comment by IndrajeetPatil** [comment]
The universe is now in balance.

![tenor](https://user-images.githubusercontent.com/11330453/120471281-cf9a9780-c3a4-11eb-927a-39ba8be84b8e.gif)

All of that sounds good to me! I will already start getting ready for a submission.

> I would even say that we could consider going out of beta (1.0.0) for the next round of release, to mark this structural update?

Agreed.

**Comment by IndrajeetPatil** [comment]
This is pretty much complete. What remains to be discussed is already being discussed in #7. 

Closing in favor of #7.
