### ISSUE TITLE
Has weighted_sd produced solid answers?

### ISSUE THREAD

**Issue by chuxinyuan** [easystats/datawizard#508]
``` r
x = c(1, 2, 3, 4)
w = c(2, 3, 4, 6)

vtable::weighted.sd(x, w)
#> [1] 1.22686
```

``` r
datawizard::weighted_sd(x, weights = w)
#> [1] 1.25996
```

``` r
z = c(1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4)
sd(z)
#> [1] 1.099784
```

``` r
weighted_mean = sum(x * w) / sum(w)
weighted_variance = sum(w * (x - weighted_mean)^2) / (sum(w) - 1)
weighted_sd = sqrt(weighted_variance)
print(weighted_sd)
#> [1] 1.099784
```

<sup>Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
his is consistent with `stats::cov.wt()`

``` r
x = c(1, 2, 3, 4)
w = c(2, 3, 4, 6)

cw <- cov.wt(cbind(x,x), w)

sqrt(cw[["cov"]])
#>         x       x
#> x 1.25996 1.25996
#> x 1.25996 1.25996
```

<sup>Created on 2024-05-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by chuxinyuan** [comment]
Hi, professor @NickCH-K,  I would also like to hear your advice on how to choose. Can you give me some help?

**Comment by NickCH-K** [comment]
There is no single definition of a weighted standard deviation (note also the availability of `HMisc::wtd.var()` which matches your by-hand calculations). The correct answer depends on what you mean to represent by it. Conveniently, [this stackexchange question](https://stats.stackexchange.com/questions/6534/how-do-i-calculate-a-weighted-standard-deviation-in-excel) has my calculation as the first answer, and the **datawizard** calculation as the second answer. If you walk through the code of both step-by-step, you see that they're identical until the last adjustment, where I divide by `(number of nonzero weights - 1)/(number of nonzero weights)`, and they divide by `1 - sum((weight/sum(weights))^2)`.

If your weights represent frequencies, then my approach is correct. If the weights represent reliability/precision of each measurement, then the **datawizard** version is correct.

**Comment by chuxinyuan** [comment]
@NickCH-K Sorry for the late reply, it is really difficult for me to log in to GitHub.

Thank you for your answer to this question. I'll determine which approach to use on a case-by-case basis.

**Comment by etiennebacher** [comment]
Closing since the `datawizard` approach is correct (at least in some context). Thank you for the explanation @NickCH-K
