### ISSUE TITLE
Failures due to compilation errors for `QuickJSR`

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#509]
Just so this is stored somewhere if someone wonders: we have some CI failures due to compilation errors for `QuickJSR`, which I had no idea we depended on.

![image](https://github.com/easystats/datawizard/assets/52219252/761be230-1d27-49af-89e1-9d9a66ac425f)

``` r
pak::pkg_deps_explain("datawizard", "QuickJSR", dependencies = TRUE)
#> ℹ Loading metadata database✔ Loading metadata database ... done
#> datawizard -> brms -> rstan -> QuickJSR
#> datawizard -> rstanarm -> rstan -> QuickJSR
#> datawizard -> rstanarm -> shinystan -> rstan -> QuickJSR
```

Should be fixed soon: https://github.com/andrjohns/QuickJSR/issues/45 (thanks @IndrajeetPatil for the report)

**Comment by IndrajeetPatil** [comment]
This is already fixed upstream; we just need to wait for binaries to be built and available on RSPM:

https://github.com/andrjohns/QuickJSR/issues/45

**Comment by IndrajeetPatil** [comment]
This should be fixed by now.
