### ISSUE TITLE
Failing CRAN checks for recent submission (0.11.0)

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#511]
For old-rel: https://cran.r-project.org/web/checks/check_results_datawizard.html

```
  Errors in running code in vignettes:
  when running code in ‘tidyverse_translation.Rmd’
    ...
  +     FUN.VALUE = logical(1)))) {
  +     evaluate_chunk <- FALSE
  + }
  
  > starwars %>% data_filter(skin_color == "light", eye_color == 
  +     "brown")
  
    When sourcing ‘tidyverse_translation.R’:
  Error: could not find function "%>%"
  Execution halted
```

Not sure, why.

**Comment by strengejacke** [comment]
We could probably have all vignettes only on our website, not on CRAN.

**Comment by etiennebacher** [comment]
Seems to me that this is a spurious error, and I didn't get any email from CRAN about this. I'd say let's wait to see if it's solved automatically or if I get some message before making vignettes less available?

**Comment by IndrajeetPatil** [comment]
I think this can be closed?

**Comment by etiennebacher** [comment]
Yes, I'll reopen if I get some message from CRAN

**Comment by strengejacke** [comment]
We could still continue with #513 and replace the magrittr pipe with the native pipe (which I personally would prefer).

**Comment by IndrajeetPatil** [comment]
This is still present with the latest release: https://cloud.r-project.org/web/checks/check_results_datawizard.html

**Comment by etiennebacher** [comment]
Which latest release? datawizard didn't get an update since this issue was open

**Comment by strengejacke** [comment]
I wonder why the CRAN issues aren't resolved yet. It's still the two failing checks due to the pipe. I'm still pro #513 :-)

**Comment by strengejacke** [comment]
Yes, I too think that this is not urgent. It's just a bit "annoying" that we have the CRAN failures across all our packages that depend on _datawizard_. And related to this, we don't have binaries for Mac OS X old-rel on CRAN - but... I don't care about OS X anyway, so I leave the decision up to you ;-)

**Comment by etiennebacher** [comment]
I didn't notice that this prevented the distribution of binaries for 0.11.0, that's annoying. I'll release 0.12.0 this week
