### ISSUE TITLE
Fix build failures on macOS 4.3

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#527]
cf. https://cloud.r-project.org/web/checks/check_results_datawizard.html

```r
Version: 0.12.1
Check: running R code from vignettes
Result: ERROR 
  Errors in running code in vignettes:
  when running code in ‘tidyverse_translation.Rmd’
    ...
  > if (!all(vapply(pkgs, requireNamespace, quietly = TRUE, 
  +     FUN.VALUE = logical(1))) || getRversion() < "4.1.0") {
  +     evaluate_chunk <- FALSE
   .... [TRUNCATED] 
  
  > row("Note: In this vignette, we use the native pipe-operator, `|>`, which was introduced in R 4.1. Users of R version 3.6 or 4.0 should replace the  ..." ... [TRUNCATED] 
  
    When sourcing ‘tidyverse_translation.R’:
  Error: a matrix-like object is required as argument to 'row'
  Execution halted
  
    ‘selection_syntax.Rmd’ using ‘UTF-8’... [1s/1s] OK
    ‘standardize_data.Rmd’ using ‘UTF-8’... [4s/5s] OK
    ‘tidyverse_translation.Rmd’ using ‘UTF-8’... failed
Flavor: [r-oldrel-macos-arm64](https://www.r-project.org/nosvn/R.check/r-oldrel-macos-arm64/datawizard-00check.html)
```

As discussed elsewhere, a solution might just be to rename the `row()` function to not collide with `base::row()`.

**Comment by etiennebacher** [comment]
I don't think this will solve it. If `base::row()` is called it means that `evaluate_chunk` was `FALSE`, so even if we rename our `row()` something like `custom_note()`, there will be an error because `custom_note()` won't be found. 

It's still a mystery why this fails only on macOS with R 4.3, but I think one solution would be to get rid of the custom function and use pure HTML, i.e. replace

````
```{r echo=FALSE}
row("Note: In this vignette, we use the native pipe-operator, `|>`, which was introduced in R 4.1. Users of R version 3.6 or 4.0 should replace the native pipe by magrittr's one (`%>%`) so that examples work.")
```
````
by
```
<div class="custom_note">
<p>
Note: In this vignette, we use the native pipe-operator, `|>`, which was introduced in R 4.1. Users of R version 3.6 or 4.0 should replace the native pipe by magrittr's one (`%>%`) so that examples work.
</p>
</div>
```

**Comment by IndrajeetPatil** [comment]
I can't even reproduce the CRAN behaviour locally on `macOS` on `R 4.3`.

I am happy with just using raw HTML to avoid this issue.

**Comment by strengejacke** [comment]
And why isn't this failing in the other vignette, from which I copied the code?

**Comment by etiennebacher** [comment]
We don't load tidyr in the other, that might the cause ?

**Comment by IndrajeetPatil** [comment]
This is still not fixed 😭, even with `0.12.2` release: 
https://www.r-project.org/nosvn/R.check/r-oldrel-macos-x86_64/datawizard-00check.html

```r
checking running R code from vignettes ... [9s/17s] ERROR
Errors in running code in vignettes:
when running code in ‘tidyverse_translation.Rmd’
  ...
+     FUN.VALUE = logical(1))) || getRversion() < "4.1.0") {
+     evaluate_chunk <- FALSE
 .... [TRUNCATED] 

> data_filter(starwars, skin_color == "light", eye_color == 
+     "brown")

  When sourcing ‘tidyverse_translation.R’:
Error: could not find function "data_filter"
Execution halted
```

Let's spend some time trying to reproduce this locally and then fix it. Otherwise, the problems are going to continue to compound.

**Comment by strengejacke** [comment]
That's more than strange, since `data_filter()` is a datawizard function. I'd say, let's move the vignettes to online only, and just refer to the overview on CRAN, like we do for _parameters_ for instance: https://cran.r-project.org/web/packages/parameters/index.html

**Comment by strengejacke** [comment]
I _think_ one reason can be that we do not use `evaluate_chunk` in every chunk. Hence, there are some chunks that are evaluated, even if they possibly shouldn't?

```r
# since we explicitely put eval = TRUE for some chunks, we can't rely on
# knitr::opts_chunk$set(eval = FALSE) at the beginning of the script. So we make
# a logical that is FALSE only if deps are not installed (cf easystats/easystats#317)
evaluate_chunk <- TRUE

if (!all(vapply(pkgs, requireNamespace, quietly = TRUE, FUN.VALUE = logical(1L))) || getRversion() < "4.1.0") {
  evaluate_chunk <- FALSE
}
```

**Comment by strengejacke** [comment]
That must be the reason. We have:

```
{r, eval = evaluate_chunk}
library(dplyr)
library(tidyr)
library(datawizard)

data(efc)
efc <- head(efc)
```

but next chunk:

```
{r filter, class.source = "datawizard"}
# ---------- datawizard -----------
starwars |>
  data_filter(
    skin_color == "light",
    eye_color == "brown"
  )
...
```

So if one of the other packages is not available, `evaluate_chunk = FALSE`, and consequently, `data_filter()` is not found. This is the behaviour that is different from the other vignette, and that's why we got a failure for `row()`.

**Comment by etiennebacher** [comment]
I'll make a PR to add the `eval=evaluate_chunk` where it's missing.

**Comment by etiennebacher** [comment]
> That must be the reason

Actually I don't think this is the reason. In the "tidyverse translation" vignette, the `eval` option is set to `FALSE` at the top. The reason is that we display the `datawizard` code and the `tidyverse` code in two code blocks (side by side) and only evaluate the datawizard one afterwards using `eval = evaluate_chunk` (and there is no place where this is missing).

R CMD check reports [this error](https://www.r-project.org/nosvn/R.check/r-oldrel-macos-x86_64/datawizard-00check.html):

> checking running R code from vignettes ... [9s/17s] ERROR
> Errors in running code in vignettes:
> when running code in ‘tidyverse_translation.Rmd’
>   ...
> +  FUN.VALUE = logical(1))) || getRversion() < "4.1.0") {
> +  evaluate_chunk <- FALSE
>  .... [TRUNCATED] 
> 
> data_filter(starwars, skin_color == "light", eye_color == 
>   "brown")
> 
>   When sourcing ‘tidyverse_translation.R’:
> Error: could not find function "data_filter"
> Execution halted

but that shouldn't be evaluated if `evaluate_chunk` is `FALSE`.

I really don't understand why this errors. The only "fix" I can see is to remove the vignettes from the package and keep them online only (as @strengejacke suggested). @IndrajeetPatil, thoughts?

**Comment by strengejacke** [comment]
_bump_ @IndrajeetPatil - maybe we should plan to submit a new fix by the end of August/early September?

**Comment by etiennebacher** [comment]
How does it work to remove vignettes from the package while keeping them on the website? Just put the vignettes folder in `.Rbuildignore`?

**Comment by strengejacke** [comment]
Yes, that should work. For some packages, I have just left an "overview" vignette, see:

https://github.com/easystats/parameters/blob/main/.Rbuildignore
https://github.com/easystats/parameters/blob/main/vignettes/overview_of_vignettes.Rmd
https://cran.r-project.org/web/packages/parameters/index.html

**Comment by etiennebacher** [comment]
![928ypf](https://github.com/user-attachments/assets/84f562af-931b-42a7-848a-c191f2f85323)
