### ISSUE TITLE
degroup() for nested models

### ISSUE THREAD

**Issue by jmgirard** [easystats/datawizard#530]
Following up on https://github.com/easystats/datawizard/issues/520:

I got confirmation on how to degroup with nested data. *Note, however, that this does not apply for data that is both nested and crossed.* So we will need some way to specify one or the other but not both (until that is figured out later too). Basically, you just have to subtract the cluster mean of the next level up. Here is an example for three-level, but the idea extends to 4 or more.

$$
\begin{align}
\text{L3} &= \bar x_{..k} \\
\text{L2} &= \bar x_{.jk} - \bar x_{..k} \\
\text{L1} &= x_{ijk} - \bar x_{.jk} \\
\end{align}
$$

- Brincks, A. M., Enders, C. K., Llabre, M. M., Bulotsky-Shearer, R. J., Prado, G., & Feaster, D. J. (2017). Centering Predictor Variables in Three-Level Contextual Models. *Multivariate Behavioral Research, 52*(2), 149–163. https://doi.org/10.1080/00273171.2016.1256753

``` r
# Setup 

df <- read.csv("https://www.alexanderdemos.org/Mixed/Sim3level.csv")
library(easystats)
#> # Attaching packages: easystats 0.7.3 (red = needs update)
#> ✖ bayestestR  0.13.2.2   ✔ correlation 0.8.5   
#> ✔ datawizard  0.12.2     ✔ effectsize  0.8.9   
#> ✔ insight     0.20.2     ✔ modelbased  0.8.8   
#> ✔ performance 0.12.2     ✔ parameters  0.22.1  
#> ✔ report      0.5.9      ✔ see         0.8.5   
#> 
#> Restart the R-Session and update packages with `easystats::easystats_update()`.
options(width = 140)

# Three-level nested example

x1 <- 
  df |> 
  data_group(School) |>
  data_modify(Math_L3M = mean(Math)) |> 
  data_group(Classroom) |> 
  data_modify(Math_L2M = mean(Math)) |> 
  data_ungroup() |> 
  data_modify(
    Math_within = Math - Math_L2M,
    Math_between_Classroom = Math_L2M - Math_L3M,
    Math_between_School = Math_L3M
  ) |> 
  data_select(exclude = c(Math_L3M, Math_L2M))

head(x1)
#>       Math ActiveTime ClassSize Classroom School StudentID Math_within Math_between_Classroom Math_between_School
#> 1 55.42604 0.06913359        18         1   Sch1         1    7.959770              -7.601612            55.06788
#> 2 54.34306 0.08462063        18         1   Sch1         2    6.876796              -7.601612            55.06788
#> 3 61.42570 0.12994557        18         1   Sch1         3   13.959435              -7.601612            55.06788
#> 4 56.12271 0.74613202        18         1   Sch1         4    8.656445              -7.601612            55.06788
#> 5 53.34900 0.03887918        18         1   Sch1         5    5.882735              -7.601612            55.06788
#> 6 57.99773 0.68563542        18         1   Sch1         6   10.531467              -7.601612            55.06788
```

<sup>Created on 2024-07-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by jmgirard** [comment]
> In your example, the data is not nested:

This may not be the best example, but this data would still be considered nested if classroom 1 is different in each school.

**Comment by strengejacke** [comment]
Can you check your script and the formula you posted? The results should be following, if I'm not mistaken:

``` r
df <- read.csv("https://www.alexanderdemos.org/Mixed/Sim3level.csv")

x_ijk <- df$Math
xbar_k <- ave(x_ijk, df$School, FUN = mean)
xbar_jk <- ave(x_ijk, df$School, df$Classroom, FUN = mean)

L3_between <- xbar_k
L2_between <- xbar_jk - xbar_k
L1_within <- x_ijk - xbar_jk

head(L3_between)
#> [1] 55.06788 55.06788 55.06788 55.06788 55.06788 55.06788
head(L2_between)
#> [1] 4.097776 4.097776 4.097776 4.097776 4.097776 4.097776
head(L1_within)
#> [1] -3.739617 -4.822592  2.260048 -3.042942 -5.816652 -1.167920
```

<sup>Created on 2024-08-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(datawizard)
df <- read.csv("https://www.alexanderdemos.org/Mixed/Sim3level.csv")
demean(df, "Math", by = c("School", "Classroom"), nested = TRUE) |> head()
#>   Math_School_between Math_Classroom_between Math_within
#> 1            55.06788               4.097776   -3.739617
#> 2            55.06788               4.097776   -4.822592
#> 3            55.06788               4.097776    2.260048
#> 4            55.06788               4.097776   -3.042942
#> 5            55.06788               4.097776   -5.816652
#> 6            55.06788               4.097776   -1.167920
```

<sup>Created on 2024-08-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@jmgirard ?

**Comment by jmgirard** [comment]
> Can you check your script and the formula you posted? The results should be following, if I'm not mistaken:
> 
> ```r
> df <- read.csv("https://www.alexanderdemos.org/Mixed/Sim3level.csv")
> 
> x_ijk <- df$Math
> xbar_k <- ave(x_ijk, df$School, FUN = mean)
> xbar_jk <- ave(x_ijk, df$School, df$Classroom, FUN = mean)
> 
> L3_between <- xbar_k
> L2_between <- xbar_jk - xbar_k
> L1_within <- x_ijk - xbar_jk
> 
> head(L3_between)
> #> [1] 55.06788 55.06788 55.06788 55.06788 55.06788 55.06788
> head(L2_between)
> #> [1] 4.097776 4.097776 4.097776 4.097776 4.097776 4.097776
> head(L1_within)
> #> [1] -3.739617 -4.822592  2.260048 -3.042942 -5.816652 -1.167920
> ```
> 
> Created on 2024-08-08 with [reprex v2.1.1](https://reprex.tidyverse.org)

This looks correct and the use of `ave()` is much more elegant than my approach. How does the user specify which factor is L3 vs L2? I assume it is descending positional and this will be clarified in the docs? Also, worth considering whether the names `Math_School_between` and `Math_Classroom_between` is preferred over `Math_L3` and `Math_L2` or something that explicitly nods to the nested structure.
