### ISSUE TITLE
Preparing CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#543]
@etiennebacher I plan to submit _insight_ shortly, which will require some packages to be submitted afterwards due to "breaking" changes (deprecation of older arguments). Among these packages is _bayestestR_, which in turn needs _datawizard_ to be on CRAN first (see https://github.com/easystats/datawizard/commit/8ac3a93832f2ab7dc10b48bc6ff861a774e432c7).

There's nothing special to do, except submitting, this is actually independent from _insight_ (must only go before _bayestestR_). Are you available the next days to submit to CRAN?

**Comment by etiennebacher** [comment]
Yes I'll be quite available in the next days, just let me know once `insight` is on CRAN

**Comment by strengejacke** [comment]
_insight_ is on CRAN. This breaks _parameters_, so we have ~ 2 weeks to submit _datawizard_ and _bayestestR_ first. :-)

**Comment by strengejacke** [comment]
Tagging @DominiqueMakowski - I think _bayestestR_ is in shape for submission, just needs _datawizard_ on CRAN first (will run final checks then).
