### ISSUE TITLE
standardize: define fixed args in the S3 method

### ISSUE THREAD

**Issue by mattansb** [easystats/datawizard#55]
You need to define the S3 method differently in _datawizard_. 

If this is the generic:

``` r
standardize <- function(x,
                        robust = FALSE,
                        two_sd = FALSE,
                        weights = NULL,
                        verbose = TRUE,
                        ...) {
  UseMethod("standardize")
}
```

Than **all** other methods need to have _at least_ these arguments.

In _datawizard_, it should be:

``` r
standardize <- function(x, ...) {
  UseMethod("standardize")
}
```

_Originally posted by @strengejacke in https://github.com/easystats/modelbased/issues/169#issuecomment-1022064061_

**Comment by strengejacke** [comment]
@IndrajeetPatil have you submitted already, or can we fix this before submission?

**Comment by IndrajeetPatil** [comment]
Nope! I am not going to submit till you tell me to submit 😄

**Comment by strengejacke** [comment]
> Nope! I am not going to submit till you tell me to submit 😄

Very good! 😄 

Looks like the failing checks are not related to my changes here...
