### ISSUE TITLE
Consistent naming schema for data wrangling and transformation functions

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#57]
https://easystats.github.io/datawizard/reference/index.html

due to aliases for some functions that start with `data_`, and pkgdown.yml using `starts_with("data")`, functions are shown under two headers.

**Comment by IndrajeetPatil** [comment]
Why do we have these aliases? 

I think only functions that have anything to do with data wrangling should carry the `data_` prefix, and the other shouldn't.

So I would vote for removing the following aliases:
- `data_adjust` (not used anywhere in the ecosystem)
- `data_to_numeric` (re-exported from _parameters_)
- `data_rescale` (this is the trickiest one since it is widely used in the ecosystem, and we have decided to prefer it over `change_rescale`)

These are the [odd ones out](https://easystats.github.io/datawizard/reference/index.html#data-transformation). 
We don't have `data_center`, `data_winsorize`, etc., so no reason to treat few transformation functions specially.

What do you think @DominiqueMakowski, @mattansb, @bwiernik?

**Comment by bwiernik** [comment]
Not sure what you are considering "data wrangling" vs not

**Comment by IndrajeetPatil** [comment]
Yeah, that's a tough question.

Roughly speaking, anything that changes the structure of how the data is stored (and relevant metadata) but leaves the **values** of the **retained** data intact.

So, for example, the following will be all data wrangling helpers:
`data_partition`, `data_relocate`, `data_remove`, `data_rename`, `data_rename_rows`, `data_reorder`, `data_to_long`,
`data_to_wide`

All the data transformation helpers are changing the values of the data. For example, 
`center`, `change_scale`, `adjust`, etc.

Does that make a little bit of sense?

**Comment by strengejacke** [comment]
I would distinguish between data frame and variable transformations. The first is "data wrangling", maybe?

**Comment by DominiqueMakowski** [comment]
I think all functions that take data as argument (and does any sort of data manipulation/transformation) should start with `data_`

**Comment by IndrajeetPatil** [comment]
Hmm, in that case, the other option is to add `data_` prefix aliases to all data transformation function (see the image below) as well.

I am fine either way, as long as we have a consistent naming schema. 

![image](https://user-images.githubusercontent.com/11330453/151309602-7cb24c47-0760-4a03-95c6-5b501f336613.png)

**Comment by DominiqueMakowski** [comment]
> I think all functions that take data as argument (and primarily do any sort of data manipulation/transformation) should start with data_

"...from now onwards" 😁

**Comment by bwiernik** [comment]
Aliases are free.

**Comment by IndrajeetPatil** [comment]
Also helps us avoid masking like these:

``` r
library(tidyr)
library(datawizard)
#> 
#> Attaching package: 'datawizard'
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
```

<sup>Created on 2022-01-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I think we should be retiring this particular alias ASAP.

**Comment by bwiernik** [comment]
It's not on CRAN yet I don't think, so rename it

**Comment by DominiqueMakowski** [comment]
(Similarly, we should probably deprecate `adjust()`, `centre()` ad `demean()` in favour of `data_*`)

**Comment by strengejacke** [comment]
Yes, this is a small inconsistency we have here:

- The name of the first argument for functions that _only_ work on data frames is `data`.
- Whenever a function also has a numeric/factor/vector method, the first arg is named `x`

(though I'm not sure this is consistent)

However, not all functions that start with `data_` _only_ work on data frames, see `data_cut()`.

This means: We _could_ rename `center()` into `data_center()` - however, I think there are some names that are too common to be named _only_ `data_*()`. But after all, `data_standardize()` or `data_center()` would make sense in the context of the naming scheme, are those names don't look too awkward.

**Comment by mattansb** [comment]
We can have `data_*()` for data frames, and `vector_*()` for vectors? It's a bit verbose, but also easy to use.

The `yardstick` package uses a somewhat similar schema (with `*()` for data frames, and `vec_*()` for vectors).

**Comment by bwiernik** [comment]
I don't see the problem with having `data_*()` accept either vector or data frame input?
