### ISSUE TITLE
Improving `ranktransform(sign = TRUE)`

### ISSUE THREAD

**Issue by mattansb** [easystats/datawizard#570]
Currently, if `x` contains 0s, these are marked as NAs.

However, there might be situations where this is unwanted (see https://github.com/easystats/effectsize/issues/502).

We can add a `zeros=` argument, that can take the values:
- `"na"` - the current method.
- `"signrank"` - keep them during the ranking and mark them as 0.

```R
if (zeros == "na") {
  out <- rep(NA, length(x))
  ZEROES <- x == 0
  out[!ZEROES] <- sign(x[!ZEROES]) * rank(abs(x[!ZEROES]), 
                                          ties.method = method,
                                          na.last = "keep")
} else if (zeros == "signrank") {
  out <- sign(x) * rank(abs(x), ties.method = method, na.last = "keep")
}
```

**Comment by etiennebacher** [comment]
Sounds good to me, @strengejacke @IndrajeetPatil thoughts?

**Comment by strengejacke** [comment]
Agree.

**Comment by IndrajeetPatil** [comment]
Thanks. 

Yes, the new argument with the mentioned default sounds like a good idea to me.
