### ISSUE TITLE
`data_rename()`: "Error: Following variable(s) were not found" in version '0.13.0.17'

### ISSUE THREAD

**Issue by rempsyc** [easystats/datawizard#571]
Yo, trying to integrate the devel version of `datawizard '0.13.0.17'` I'm facing a breaking change in `data_rename()` (more info in easystats/report#470). Just wanted to check with you if that's something I should change in `report` or `datawizard`. My attempt at a minimal reprex:

### `datawizard` '0.13.0.17'

``` r
packageVersion("datawizard")
#> [1] '0.13.0.17'

result <- list(
  setosa.a = structure(data.frame(1)), 
  versicolor.a = structure(data.frame(2)))

new_names <- c("setosa, a", "versicolor, a")

names(result)
#> [1] "setosa.a"     "versicolor.a"
new_names
#> [1] "setosa, a"     "versicolor, a"

datawizard::data_rename(result, select = names(result), replacement = new_names)
#> Error: Following variable(s) were not found: setosa.a, versicolor.a
#>   Possibly misspelled?
```

<sup>Created on 2024-12-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### `datawizard` '0.13.0'

``` r
packageVersion("datawizard")
#> [1] '0.13.0'

result <- list(
  setosa.a = structure(data.frame(1)), 
  versicolor.a = structure(data.frame(2)))

new_names <- c("setosa, a", "versicolor, a")

names(result)
#> [1] "setosa.a"     "versicolor.a"
new_names
#> [1] "setosa, a"     "versicolor, a"

datawizard::data_rename(result, select = names(result), replacement = new_names)
#> $`setosa, a`
#>   X1
#> 1  1
#> 
#> $`versicolor, a`
#>   X2
#> 1  2
```

<sup>Created on 2024-12-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The reason seems to be that `data_rename()` searches for all the variables mentioned in select for each data frame of the list, but each name only appears once in their respective data frame. Therefore, some variables are bound to not be found. So, whereas `data_rename()` used to work on lists, now it only works on dataframes? This seems to break `report::report_sample` tests.

**Comment by strengejacke** [comment]
Note that you cannot use the `safe` argument in future versions and have to check if names (in `select`) really exist.

**Comment by strengejacke** [comment]
I think so, too. I don't think this was actually intentional. You could use `setNames()` as a workaround in this particular situation, @rempsyc

**Comment by strengejacke** [comment]
Yes, thought about that, too. I think this mostly makes sense for data frames. The alternative would be to revise `.select_nse()`, to it also works with list. Haven't looked into the details whether this can be done easily.

**Comment by rempsyc** [comment]
Yes, agreed, it would make sense for consistency that it works only on data frames. And, it was only used that way once in report, so I was able to switch it to `setNames()` like Daniel suggested. Perhaps we should simply have a more informative error on lists, or, as you mention, not attempt to coerce.
