### ISSUE TITLE
Append results of `demean()` to original df?

### ISSUE THREAD

**Issue by mattansb** [easystats/datawizard#578]
99% of the time was want to append the results of the `demean()` to the original data frame. Can we have that as an option (or maybe even the default)?

**Comment by strengejacke** [comment]
Yes, makes sense

**Comment by mattansb** [comment]
Is this as easy as adding a `cbind()` at the end of the function?

**Comment by strengejacke** [comment]
> Is this as easy as adding a `cbind()` at the end of the function?

Almost. Since we're _easystats_, we give informative errors/warnings/messages for ever imaginable exceptions users can run into :-)

**Comment by mattansb** [comment]
Ha, of course!

**Comment by strengejacke** [comment]
Ok, add Your review please😎
