### ISSUE TITLE
Writing a JOSS paper

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#59]
Once the API is more stable (which should be the case in a few months), we should definitely do this.

**Comment by IndrajeetPatil** [comment]
Submitting the paper today.

**Comment by IndrajeetPatil** [comment]
The PDF for the most recent version of the paper can always be found here: 
https://github.com/easystats/datawizard/actions/workflows/draft-pdf.yml

DO NOT remove the related GitHub action because JOSS uses this action to build the paper.

**Comment by IndrajeetPatil** [comment]
The paper is now under review: https://github.com/openjournals/joss-reviews/issues/4684

**Comment by strengejacke** [comment]
Thanks for all the work on this paper!
