### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/datawizard#6]
Unfortunately we don't have the rights to gandalf :p 

I made a [first draft](https://github.com/easystats/easystats/blob/master/man/figures/datawizard/logo.png) with a monster-wizard tidying-up a bunch of data (cells)

![logo](https://user-images.githubusercontent.com/8875533/119763039-6537b200-bee1-11eb-8c2f-2d30b9962e53.png)

**Comment by DominiqueMakowski** [comment]
I found the monster [here](https://www.flaticon.com/search?word=monster), but there might cuter ones lol

**Comment by IndrajeetPatil** [comment]
I love it!!! Really cute (and colorful) ❤️

**Comment by strengejacke** [comment]
I would probably choose a "face" that looks less desperate and failing with the tasks ;-) The eyes suggest some confusion, as if the package is overburdening you.

**Comment by strengejacke** [comment]
What about these ones?

https://www.flaticon.com/free-icon/monster_1492545?related_id=1492545&origin=search
https://www.flaticon.com/free-icon/cyclops_1236137

**Comment by strengejacke** [comment]
Or here: https://www.flaticon.com/free-icon/monster_1236125?term=monster&page=3&position=89&page=3&position=89&related_id=1236125&origin=search

**Comment by IndrajeetPatil** [comment]
> Or here: https://www.flaticon.com/free-icon/monster_1236125?term=monster&page=3&position=89&page=3&position=89&related_id=1236125&origin=search

I like this one!

**Comment by DominiqueMakowski** [comment]
lemem give it a go :)

**Comment by DominiqueMakowski** [comment]
I removed the black borders which makes it more flat and sleek (more in style of `see` than the other packages tho), whadayathink?


![logo](https://user-images.githubusercontent.com/8875533/119816220-0b55dd00-bf1f-11eb-8fce-39058b834752.png)

**Comment by DominiqueMakowski** [comment]
I edited the hat to make it more in line with the rest and rebalanced the background so it's more symetrical

![logo](https://user-images.githubusercontent.com/8875533/119817114-270db300-bf20-11eb-8f97-afa9484fbd1f.png)

**Comment by strengejacke** [comment]
yeah, that looks good!

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/datawizard#datawizard Looking at it in the readme; maybe I should try brightening up the monster or the background it's a bit dark, I'll try a few things tomorrow

**Comment by DominiqueMakowski** [comment]
![logo](https://user-images.githubusercontent.com/8875533/120054234-4ceea100-c061-11eb-86e4-7efa405f3c67.png)


I recolored a bit and made the little stars bigger so that it looks hopefully better with smaller resolutions

**Comment by DominiqueMakowski** [comment]
feel free to re-open if anything :)
