### ISSUE TITLE
Move `.get_dot_data()` to`WIP` folder

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#64]
@strengejacke Can this be removed? It's not used anywhere, either in this package or the larger ecosystem.

https://github.com/easystats/datawizard/blob/c99114587b05b074a043991a3a80ee66ab6d26e1/R/utils_get_dots.R

**Comment by strengejacke** [comment]
I think we added this as a draft for implementing select helpers. I recall @bwiernik suggested adding this feature, I think it was related to the use of the `drop` and `keep` arguments in _parameters_.

**Comment by strengejacke** [comment]
We could move it to a WIP folder, maybe?

**Comment by bwiernik** [comment]
Yes, that was the plan

**Comment by IndrajeetPatil** [comment]
These functions now live in `WIP` folder.
