### ISSUE TITLE
set_na()

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#67]
If we're going to copy some useful functions from sj* packages, we should also have a `set_na()` function. This is a quite common operation after importing data from Stata or SPSS.

**Comment by IndrajeetPatil** [comment]
Is this the same as `replace_na()`?

**Comment by strengejacke** [comment]
No, I think it's the counter-part.

replace_na = replace NA with a value, i.e. turn NAs into a non-NA value
set_na = replace values with NA, i.e. replace specific values with NA.

**Comment by IndrajeetPatil** [comment]
Ah, I see. Hadn't come across it.

How do you feel about naming it `convert_to_na()`?
