### ISSUE TITLE
docs for data_rename() et al.

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#69]
The meaning / usage of each function here is not really obvious / intuitive:
https://easystats.github.io/datawizard/reference/data_rename.html

We should probably add short descriptions to a "details" section.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski Do you want to take this one on? If I remember correctly, you had implemented these. 

I am also wondering if there is a vignette in order for covering all the functionality (reshaping, merging, renaming, relocating, etc.) offered by `data_` functions?

**Comment by strengejacke** [comment]
_bump_ I think this is rather important, even I don't know what some of the functions or arguments are supposed to do.

**Comment by strengejacke** [comment]
I think we should split the docs here:

- renaming columns
  => `data_addprefix()`, `data_addsuffix()` and `data_rename()` 

- reordering/removing columns
  => `data_remove()` and `data_reorder()` 

- the rest
  => `data_rename_rows()` and `data_findcols()`

**Comment by DominiqueMakowski** [comment]
Will do that now
