### ISSUE TITLE
duplicated functions?

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#70]
Aren't https://easystats.github.io/datawizard/reference/data_transpose.html and https://easystats.github.io/datawizard/reference/data_rotate.html the same?

**Comment by strengejacke** [comment]
@IndrajeetPatil I have moved _data_transposed.R_ to _WIP_, added an alias to `data_merge()` and added the feature that rownames are used as colnames by default, if not specified otherwise.

**Comment by IndrajeetPatil** [comment]
Thanks!

It's used only in two other places, so this change shouldn't cause any trouble. 
https://github.com/search?l=R&q=org%3Aeasystats+data_transpose&type=Code

**Comment by strengejacke** [comment]
And the results are actually identical with the default arguments.
