### ISSUE TITLE
Is `convert_data_to_numeric.character()` working as expected?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#73]
I am not sure that the regular expression is doing its job here:
https://github.com/easystats/datawizard/blob/aa18edf465c593dd3256e9e8c8039e77b629e169/R/convert_data_to_numeric.R#L64-L72

``` r
library(datawizard)

convert_data_to_numeric(c("abc", "xyz"))
#> [1] 1 1

convert_data_to_numeric(c("123", "789"))
#> [1] 1 1
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke You are the regex expert. It's not working as expected, right?

**Comment by strengejacke** [comment]
I'm the expert in asking regex-questions, not answering them ;-)
I'm 99% sure that regex is not from me. Looks like the intention is that when we have strings like `"1e-3"` or `"2L"`, these should be converted into proper numerics... I'll try to see if I find a way how to do this...

**Comment by strengejacke** [comment]
What about this one:

``` r
n <- "1L"
tryCatch(str2lang(n), error = function(e) NULL)
#> [1] 1

n <- "3e-5"
tryCatch(str2lang(n), error = function(e) NULL)
#> [1] 3e-05

n <- "3B"
tryCatch(str2lang(n), error = function(e) NULL)
#> NULL

n <- "3a-5"
tryCatch(str2lang(n), error = function(e) NULL)
#> NULL
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We have a `str2lang()` re-export in inside, to be compatible with R < 3.6

**Comment by strengejacke** [comment]
The code should be:

``` r
n <- c("1L", "3e-5", "A")
all(sapply(n, function(i) {
  nums <- tryCatch(str2lang(i), error = function(e) NULL)
  !is.null(nums) && is.numeric(nums)
}))
#> [1] FALSE


n <- c("1L", "3e-5", "543")
all(sapply(n, function(i) {
  nums <- tryCatch(str2lang(i), error = function(e) NULL)
  !is.null(nums) && is.numeric(nums)
}))
#> [1] TRUE
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
should be fixed:

``` r
library(datawizard)

convert_data_to_numeric(c("abc", "xyz"))
#> [1] 1 2

convert_data_to_numeric(c("123", "789"))
#> [1] 123 789

convert_data_to_numeric(c("1L", "2e-3"))
#> [1] 1.000 0.002

convert_data_to_numeric(c("1L", "2e-3", "ABC"))
#> [1] 1 2 3
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I just saw tests have to be fixed, too:

```
── Failure (test-convert_data_to_numeric.R:7:3): convert character to numeric ──
convert_data_to_numeric(c("xyz", "ab")) (`actual`) not equal to c(1, 1) (`expected`).

  `actual`: 2 1
`expected`: 1 1
```

I would say that `convert_data_to_numeric(c("xyz", "ab"))` should return `2 1`, because this is really what `as.numeric(as.factor(c("xyz", "ab")))` does (1 and 1 doesn't make sense, because we have two different values here).

**Comment by IndrajeetPatil** [comment]
Thanks!

I can take care of changing the tests.

**Comment by strengejacke** [comment]
just added tests
