### ISSUE TITLE
why are github actions not working?!

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#8]
Really surprising since this is exactly the infrastructure we have across the entire ecosystem.

**Comment by strengejacke** [comment]
I guess it's temporary.

**Comment by IndrajeetPatil** [comment]
But it has never worked with this repo. Not a single commit since the birth of this repo has triggered github actions.

**Comment by strengejacke** [comment]
Ah, ok. I'll look into it.

**Comment by strengejacke** [comment]
You're on the master branch, the actions work for the main branch.

**Comment by IndrajeetPatil** [comment]
Huh, weird. I thought GitHub now defaults to `main` instead of `master`.

Thanks!
