### ISSUE TITLE
Shouldn't data_match() return a data frame?

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#82]
What is the rational behind returning the row-indices? We could add an argument to trigger whether to return row indices or a data frame.

**Comment by strengejacke** [comment]
Ok, @IndrajeetPatil I think I'm done for today (i.e. no more bunches of commits now ;-))

will add more tests on labelled data when I stumble upon issues when working with _datawizard_.

**Comment by IndrajeetPatil** [comment]
I am not sure why it was this way. @DominiqueMakowski had implemented this function, and maybe he had a use case for this?

At any rate, I see that the changes you made are backward compatible, so this shouldn't be an issue.

**Comment by strengejacke** [comment]
Where is this function used throughout our packages? Maybe we can soft-deprecate the current behaviour and change the default to returning a data frame in a future update?

**Comment by DominiqueMakowski** [comment]
I did had a use case (https://github.com/easystats/modelbased/blob/c9f54258d79efd56253d6ceab70f3428f7dacf32/R/estimate_slopes.R#L177), but yeah it makes sense to extend the function like this

**Comment by IndrajeetPatil** [comment]
Keeping this open as a reminder to change the default argument.

**Comment by IndrajeetPatil** [comment]
Closed in #126
