### ISSUE TITLE
Is `{datawizard}` the right place for demean vignette?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#91]
@easystats/maintainers  

IMHO, the [demean](https://easystats.github.io/datawizard/articles/demean.html) vignette should live in a higher-level package specializing in dealing with regression model objects (like `{parameters}`), and not in a relatively low-level package like `{datawizard}`, which doesn't have much to do with regression analysis.

What do you think?

(P.S. In case you are worried about such a vignette displacement breaking existing URLs, that shouldn't be an issue. We can use a forwarding strategy to protect against it.)

**Comment by strengejacke** [comment]
It _was_ in _parameters_, but moved with the `demean()` function to _datawizard_.

**Comment by strengejacke** [comment]
But I agree with you. Feel free to move it back.

**Comment by strengejacke** [comment]
Note that vignettes are not on CRAN. We only have this overview:
https://github.com/easystats/parameters/blob/main/vignettes/overview_of_vignettes.Rmd

**Comment by IndrajeetPatil** [comment]
Done. 

In _datawizard_, should I just remove the vignette, or keep the vignette and add the new URL on _parameters_ website for this vignette?

**Comment by strengejacke** [comment]
As you like.
