### ISSUE TITLE
data_rename() should error if no pattern and too small replacement

### ISSUE THREAD

**Issue by etiennebacher** [easystats/datawizard#98]
Consider the example below:
``` r
library(datawizard)
data_rename(head(iris), replacement = "foo")

#>   foo  NA  NA  NA     NA
#> 1 5.1 3.5 1.4 0.2 setosa
#> 2 4.9 3.0 1.4 0.2 setosa
#> 3 4.7 3.2 1.3 0.2 setosa
#> 4 4.6 3.1 1.5 0.2 setosa
#> 5 5.0 3.6 1.4 0.2 setosa
#> 6 5.4 3.9 1.7 0.4 setosa
```
<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When `pattern = NULL` (default), all columns are selected to be renamed. In this case, I think `data_rename()` shouldn't run if the replacement is different than the number of columns, or at least should warn the user that some columns are called `NA`. (Happy to PR later if needed)

**Comment by strengejacke** [comment]
Yes, sounds reasonable. Would be great if you can open a PR.

**Comment by etiennebacher** [comment]
Also, these lines in `data_rename()` are weird to me:
https://github.com/easystats/datawizard/blob/c4c484d48ed5c4832ced1be85889b5001baa38dd/R/data_rename.R#L52-L55

Why would the pattern be used to replace the names if there are no replacement specified? I think this case should throw an error as well.

**Comment by strengejacke** [comment]
Yes. And when we're already improving it, we should check for name collisions in the replacement, and then add a suffix to avoid duplicated column names. And we could, if replacement is shorter than ncol() and pattern = NULL, maybe just rename the first columns (from 1:lengt(replacement)).
